### ISSUE TITLE
pip version differs between Python version + virtualenv

### ISSUE THREAD

**Issue by keikoro** [pyenv/pyenv-virtualenv#177]
I'm not entirely sure what the expected behaviour for this is/should be, but I noticed that the `pip` version used for `virtualenv`s created from a Python version does not necessarily reflect the pip version used by that Python version.

Is there a way to make all virtualenvs reflect the pip version of the Python version they are based on?

Test output:

```
$ pyenv version
3.5.1 (set by MYHOME/.pyenv/version)

$ pip --version
pip 8.1.2 from MYHOME/.pyenv/versions/3.5.1/lib/python3.5/site-packages (python 3.5)

$ pyenv virtualenv 3.5.1 piptest
Ignoring indexes: https://pypi.python.org/simple
Requirement already satisfied (use --upgrade to upgrade): setuptools in MYHOME/.pyenv/versions/3.5.1/envs/piptest/lib/python3.5/site-packages
Requirement already satisfied (use --upgrade to upgrade): pip in MYHOME/.pyenv/versions/3.5.1/envs/piptest/lib/python3.5/site-packages

$ pyenv activate piptest
pyenv-virtualenv: deactivate
pyenv-virtualenv: activate piptest
pyenv-virtualenv: prompt changing will be removed from future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior.

$ pip --version
pip 7.1.2 from MYHOME/.pyenv/versions/3.5.1/envs/piptest/lib/python3.5/site-packages (python 3.5)
```

In case it matters: `8.1.2` was not the original pip version of my Python `3.5.1`. I upgraded it when pip told me it was ready to upgrade:

```
$ pip freeze
(...)
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
##

**Comment by yyuu** [comment]
Actually pyenv-virtualenv doesn't manage version of virtualenv and pip by default. The version of `pip` in virtualenv will be managed by `virtualenv` (or, `pyvenv` if you're on 3.3+). I guess `virtualenv` installed in your 3.5.1 must be 15.0.1 which bundles pip 8.1.1.

https://github.com/pypa/virtualenv/tree/15.0.1/virtualenv_support

**Comment by native-api** [comment]
If `virtualenv` substitutes its own Pip version, there's little we can or should do. Monkey-patching `virtualenv`, setting envvars etc would only bring more confusion.

Unless there are very compelling reasons to override `virtualenv`'s logic, we probably shouldn't touch it.
