### ISSUE TITLE
Failled to activate pyenv virtualenv from tmux

### ISSUE THREAD

**Issue by AliusEquinox** [pyenv/pyenv-virtualenv#189]
I cannot use pyenv virtualenv when I run it under tmux.

It works well without outside of tmux and I can use and active my virtualenvs, but when I run pyenv activate <myenv> I have an error " Failed to activate virtualenv. Perhaps pyenv-virtualenv hos not been load into your shell properly.

the PATH is the same in both cases including pyenv and pyenv-virtualenv shims...
I initialize pyenv and pyenv-virtualenv in the .bash_profile script

any idea about this error ?
##

**Comment by blueyed** [comment]
The environment in the tmux session is different, and it depends on where you start `tmux`.

Compare the complete env (`env | sort`) and maybe also the output with `export PYENV_DEBUG=1` from both invocations.
Also try using `.bashrc` instead of `.bash_profile` maybe.

**Comment by lwm** [comment]
I was having a similar issue but using Zsh. Moving initialisation into my `.zshenv` worked. 

Any resolution to this @AliusEquinox?

**Comment by ibeex** [comment]
@lwm I tried to move initialization to .zshenv and it still don't work.

**Comment by blueyed** [comment]
Closing then.
Please provide the output from my previous comment to help debugging you this further, if it comes up again.
