### ISSUE TITLE
Add `pyenv virtualenv-init` to `.zprofile` instead of `.zshenv`, maybe?

### ISSUE THREAD

**Issue by levblanc** [pyenv/pyenv-virtualenv#192]
Hi, I am totally new to shell programming and python. I found `pyenv` and `pyenv-virtualenv` just because I want to install flask with python 3.4, while my system python version is 2.7. (I am on mac OS X EI Capitan 10.11.6, iTerm2 Build 3.0.10)

After installed both of them on my machine, I followed the instruction and added the following two lines in to my `~/.zshenv`: 

```
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
```

Everything worked well when I installed python 3.4.3 with `pyenv`, so was the `pyenv virtualenv` creation.

But when I tried to install flask under the folder with the virtual env, `pip` yelled at me, saying that my current account didn't have permission to access system's python folders, and I could see `pip` was pointing to the system version of python.

This made me feel like the lines in `~/.zshenv` was not working. After many tries on creating new iterm tabs and restarting iterm itself, problem still existed.

Then, under the folder with virtual env created (and set pyenv local), I tried : 

```
$ which python
/usr/bin/python
```

By comparing to the readme file, this suggests that the shims were not working, right? Then I echo the `$PATH`, no shims part: 

```
$ echo $PATH
/Users/levblanc/.nvm/versions/node/v4.4.4/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
```

Then I found this question: 
[.zshenv not sourced on ssh login?](http://unix.stackexchange.com/questions/272123/zshenv-not-sourced-on-ssh-login?newreg=4b6f7c8d3aa34a3ca1df255b6ea11b94)

and tried to move the two config lines to `.zprofile`.

Everything works like magic now.  No more permission denied, `pip` is now pointing to the right place. 

PS:
I also found answers said the `/etc/zprofile` file would overwrite `.zshenv` settings.

I have in following lines in it: 

```
# system-wide environment settings for zsh(1)
if [ -x /usr/libexec/path_helper ]; then
	eval `/usr/libexec/path_helper -s`
fi
```

and I do have `/usr/libexec/path_helper` on my machine.

I am confused by all these config files, when and where to put things in ....

**Comment by gwerbin** [comment]
You definitely shouldn't have `pyenv` in your `.zshenv`. See http://zsh.sourceforge.net/Doc/Release/Files.html#Files for an explanation of which files are sourced when.

**Comment by levblanc** [comment]
The doc says so (see quote below), that's why I put it into my `.zshenv`, and that's why I open this issue.

> Add pyenv virtualenv-init to your shell to enable auto-activation of virtualenvs. 
> ......
> ...
> Zsh note: Modify your ~/.zshenv file instead of ~/.bash_profile. 

But now they are in my `.zshprofile` and everything works fine.
So my thoughts are:  

"I am sure `.zshprofile` is the right place."
"But since the doc says so, maybe I did something wrong along the way"

haha

**Comment by blueyed** [comment]
zprofile/bash_profile is better performance-wise, but you cannot define functions (like `pyenv()` from `pyenv init -`) in `~/.zprofile` on Linux typically, where no login shell will be used for new terminal instances (but only for the (GUI) login shell).

I am using a mixture of `~/.zprofile` (PATH, PYENV_ROOT) and `~/.zshrc` myself (custom `pyenv` function for lazy loading).

pyenv/pyenv-virtualenv's README recommends to use `zshenv` though indeed: it looks like c6855e0 ("zshenv -> zshrc. update Ubuntu/zsh installation notices") was not merged correctly from rbenv.

See also https://github.com/rbenv/rbenv/wiki/Unix-shell-initialization.

@levblanc 
So my guess is that either you are running a login shell for every new terminal, or that you are missing the function part(s) of the init procedure (i.e. the precmd function for pyenv-virtualenv).. which is not really necessary for pyenv-virtualenv, but with `pyenv` you should have a function that can handle the `activate|deactivate|rehash|shell` commands (by `eval`ing them).

Would you be up for tackling that? :)
(i.e. compare the README(s) (pyenv/pyenv-virtualenv) with what rbenv has, and create a PR for pyenv/pyenv-virtualenv)

**Comment by gwerbin** [comment]
For what it's worth I actually have Pyenv in my Zshrc. The modified path gets inherited by subshells and I never seem to have a problem.

That said you could also source your zprofile at the top of your zshrc. That's a standard gimmick in Bash. As far as I can tell, the whole idea of a login vs non-login shell is a little antiquated anyway.

But yes, on OSX all new shells are login shells by default.

**Comment by blueyed** [comment]
> For what it's worth I actually have Pyenv in my Zshrc. The modified path gets inherited by subshells and I never seem to have a problem.

I do not expect any problems in this case, but am more considered about overhead.
Therefore I lazy-load pyenv only when it is being used for the first time - and only then the version gets displayed in the prompt etc.

> That said you could also source your zprofile at the top of your zshrc

Well, what's the point in splitting it then?

> That's a standard gimmick in Bash.

No, that's actually required in Bash, not a gimmick - since it will not load the profile for non-login shells.

**Comment by levblanc** [comment]
@blueyed 
I am on mac OSX and my shells are login shells.
I only have the following lines in my `.zprofile`, no  "function part(s)" : 

```
if which pyenv > /dev/null; then eval "$(pyenv init -)"; fi

if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
```

I am not sure whether I understand what you meant by `eval`ing those commands (no previous experience in shell programming, sorry), so I tried in my own understanding:

```
$: eval pyenv activate venv34
>  pyenv-virtualenv: version `venv34' is already activated
```

```
$: eval pyenv deactivate venv34
>  (nothing logged, opened new prompt in next line)
```

```
$: eval pyenv rehash
>  (nothing logged, opened new prompt in next line)
```

```
$: eval pyenv shell venv34
>  (nothing logged, opened new prompt in next line)
```

Hope these helps.

**Comment by Akronix** [comment]
I did:
`echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.zshenv`
as the README says, and I get this error when opening a new shell:

> /home/akronix/.zshenv:1: command not found: pyenv

However, adding it to zshrc it does work:
`echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.zshrc`

**Comment by gwerbin** [comment]
@Akronix that's because your `PATH` probably isn't set in Zshenv. As I mentioned, I strongly do not recommend initializing Pyenv in Zshenv. Zshrc is the correct location, from the perspective of intended Zsh semantics.

**Comment by Akronix** [comment]
> @Akronix that's because your PATH probably isn't set in Zshenv. As I mentioned, I strongly do not recommend initializing Pyenv in Zshenv. Zshrc is the correct location, from the perspective of intended Zsh semantics.

The README of the repo should be updated then.

**Comment by sshishov** [comment]
I had the same issue and tried to solve it without moving the code around. But appeared `.zshenv` is not a proper place even if I define `PATH` variable properly. It is still `evaling` everything but the python version is system's one.

Please update README to properly support ZSH as a lot of users use this shell.

**Comment by blueyed** [comment]
I guess PRs are welcome, but there might be some even already.
Also see my comment from 2016: https://github.com/pyenv/pyenv-virtualenv/issues/192#issuecomment-267298104
In general you do not need pyenv-virtualenv even, you know? :)

**Comment by tekumara** [comment]
@blueyed there's been a PR to modify the README to use `.zshrc` instead of `. zshenv`, but it was closed https://github.com/pyenv/pyenv-virtualenv/pull/167

**Comment by Akronix** [comment]
> In general you do not need pyenv-virtualenv even, you know? :)

Don't I? what do you use then @blueyed ?

**Comment by blueyed** [comment]
@Akronix 
I am using pyenv to install/manage different Python version, but https://github.com/Tarrasch/zsh-autoenv then to activate virtualenvs for different projects (which I typically install using `python -m venv .venv` there, and zsh-autoenv (or other tools) then activate it automatically; zsh-autoenv has a recipe, but requires Zsh obviously).  You can also use e.g. ´~/.pyenv/versions/…/bin/python -m venv .venv` directly instead of going through (installed/activated) pyenv obviously.
From my experience pyenv/pyenv-virtualenv's shell installation adds quite some overhead to startup by default, and is often not needed.  That's also why I am reluctant to just stash it into zshrc, if zprofile typically is enough (but it depends on your setup etc).

**Comment by blueyed** [comment]
As for this issue: I see that .zshenv is used in the readme, and it appears to work for the author (#167).

If you get errors due to pyenv not being found this could mean that e.g. you're installing pyenv then only (later) in your zshrc or similar, for example.

**Comment by Akronix** [comment]
> @Akronix
> I am using pyenv to install/manage different Python version, but https://github.com/Tarrasch/zsh-autoenv then to activate virtualenvs for different projects (which I typically install using `python -m venv .venv` there, and zsh-autoenv (or other tools) then activate it automatically; zsh-autoenv has a recipe, but requires Zsh obviously). You can also use e.g. ´~/.pyenv/versions/…/bin/python -m venv .venv` directly instead of going through (installed/activated) pyenv obviously.
> From my experience pyenv/pyenv-virtualenv's shell installation adds quite some overhead to startup by default, and is often not needed. That's also why I am reluctant to just stash it into zshrc, if zprofile typically is enough (but it depends on your setup etc).

While it's true that I've noticed some overhead when using pyenv, I find it more comfortable than having to write text files which, although they are very powerful, they'll be just for activating a virtualenv. I've used smartcd in the past and I find pyenv way more convenient.

**Comment by valhuber** [comment]
I am here searching for a simple answer like everyone else.  Buyer beware, but this is what appears to work for me:

.zshrc:
```
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi

setopt interactive_comments

sh ~/PythonStatus.sh
```

.zprofile:
```
export PATH="/usr/local/opt/python/libexec/bin:$PATH"
```

Finally, because I am tired of guessing what's where, PythonStatus.sh:
```
#!/bin/bash -x

echo ""
echo "StatusOfPthon here"
echo ""
echo "pyenv version: "
pyenv --version
echo ""
echo "pyenv global: "
pyenv global
echo ""
echo "pyenv version-name: "
pyenv version-name
echo ""
echo "virtualenv version-name: "
virtualenv --version
echo ""
echo "python: "
python --version
echo ""
```

Hope that helps, or at least doesn't hurt...

**Comment by native-api** [comment]
The current README suggests putting the init line to `.zshrc`. So this is probably no longer relevant.
