### ISSUE TITLE
How to make a postmkvirtualenv hook

### ISSUE THREAD

**Issue by ejmg** [pyenv/pyenv-virtualenv#195]
Hi there and thanks for such a great dev tool!

This is a question similar to the one asked earlier, [here](https://github.com/yyuu/pyenv-virtualenv/issues/55), but involves making a hook that executes *once and only once* after the creation of a new virtualenv.

Ideally, I would like to make a hook that automatically installs four packages in each new virtualenv I make via `pyenv`. The parallel function in virtualenvwrapper is `postmkvirtualenv`, and a user has used it for exactly this behavior as shown in `virtualenvwrapper`'s [docs](http://virtualenvwrapper.readthedocs.io/en/latest/tips.html#installing-common-tools-automatically-in-new-environments). 

I use these packages universally, irrespective of which python version I work on, and so this would save me a simple keystroke. These packages are jedi, flake8, importmagic, and autopep8.

I noticed that there was a `hook` function built in `pyenv` but haven't been able to find much documentation on how to make (what I believe to be) this simple hook. I'd appreciate any help!

**Comment by jjlorenzo** [comment]
did you find a solution for this?

**Comment by ejmg** [comment]
Haven't had the time, unfortunately. I suspect it's fairly straight forward
given how lazy of a hook this is. If you're triaging issues on this repo,
feel free to close the issue.

**Comment by lbillinghamtn** [comment]
Think I may have seen the solution to this over on SO https://stackoverflow.com/a/54627516
Hope you don't mind me leaving it as a comment here as this issue is always the 1st place I end up when searching for how to do `postmkvirtualenv`-ish stuff with `pyenv-virtualenv`

`~/.pyenv/pyenv.d/virtualenvafter.bash`

```bash
upgrade_packages() {
  PYENV_VERSION=$VIRTUALENV_NAME pyenv-exec pip install --upgrade pip setuptools wheel
}

after_virtualenv 'upgrade_packages'
```
