### ISSUE TITLE
How to "_switch_" the python version for a virtualenv?

### ISSUE THREAD

**Issue by karfau** [pyenv/pyenv-virtualenv#199]
I love how pyenv enables switching back and forth between python versions.
What I don't understand:

- Assume I have created the virtualenv for my project called `backend` for the python version 2.7.5 (.python-version is containing `2.7.5`)
- Now we want to update the python version that we use with the project to 2.7.13

My first attempt was executing `pyenv virtualenv 2.7.13 backend` but this failed because the name is already in use.

Should I attach the version to the name of the virtualenv like `backend-2.7.5` vs `backend-2.7.13` to be able to roll back when something goes wrong (e.g. SSL related breaking changes like the one in 2.7.9)?
Or what other approaches are there to make switching versions work smoothly when using virtualenvs?

As mentioned in #190 we would really like to use `.python-version` file to fix the python version used for the project. Using a virtualenv name containing the version would allow this based on some convention for the name, but it feels hacky and isn't an enforcement like it would be to have only the version number inside the file. (I don't want to rasie the same question as in #190 here again, this is just an addition to give more context/ more of my thoughts.)

Best Christian

**Comment by setu4993** [comment]
@karfau : Did you find a solution to this? Just stumbled upon this issue when trying to do something similar.

**Comment by setu4993** [comment]
`pyenv virtualenv 2.7.13 backend -f` should work. I just tried it and it continues to host previously installed packages.

**Comment by native-api** [comment]
> `pyenv virtualenv 2.7.13 backend -f` should work. I just tried it and it continues to host previously installed packages.

Indeed it does. However, those previously installed packages may not be compatible with the new host version (e.g. if they contain extenstions).

https://github.com/pyenv/pyenv-pip-migrate does the migration in a cleaner way by doing `pip freeze` and `pip install`.
