### ISSUE TITLE
potentially missing symlink: include/python3.6.m

### ISSUE THREAD

**Issue by mkassner** [pyenv/pyenv-virtualenv#200]
For compiling opencv and python-boost against a pyenv python I had to add the following link:

 `~/.pyenv/versions/{envname}/include/python3.6` 
pointing to
` ~/.pyenv/versions/3.6.0/include/python3.6.m` 

I think this should be added by default.

This issue was move from https://github.com/yyuu/pyenv-installer/issues/52

**Comment by blueyed** [comment]
Maybe related to https://github.com/pyenv/pyenv-virtualenv/issues/206 also?

**Comment by rocchidavide** [comment]
So how to solve it?

**Comment by blueyed** [comment]
@rocchidavide 
Tell us about your investigations first maybe? ;)

**Comment by native-api** [comment]
As per [Issue 43334: venv does not install libpython - Python tracker](https://bugs.python.org/issue43334), the official CPython devs' position is that development files are not supposed to be present in venvs.
