### ISSUE TITLE
pyenv seems to auto switch python bin without needing eval "$(pyenv virtualenv-init - )"

### ISSUE THREAD

**Issue by dosentmatter** [pyenv/pyenv-virtualenv#205]
Even without running eval "$(pyenv virtualenv-init - )", pyenv seems to switch to virtual versions if pyenv local is used to create a .python-version.

Here is an example without running eval "$(pyenv virtualenv-init - )":
https://asciinema.org/a/47klnxla2inotlwdris5n82rk

Notice that it switched to virtual environments venv2.7.12 and venv3.5.2. My pyenv global is 3.6.0.

Here is an example with running eval "$(pyenv virtualenv-init - )":
https://asciinema.org/a/5ghls7e02tuafw8rmn5xwv9tw

Notice that it is still switching to virtual environments venv2.7.12 and venv3.5.2. My pyenv global is still 3.6.0. The only difference is that they are activated and deactivated causing the prompt to change to something like (venv3.5.2).

Does activation and deactivation do anything besides adding the (venv3.5.2) to the shell prompt?

venv guide says activation is purely a convenience that adds the new python bin to your PATH:
https://virtualenv.pypa.io/en/stable/userguide/#activate-script
But this seems to be done already without running eval "$(pyenv virtualenv-init - )" for the activation.

Also running eval "$(pyenv virtualenv-init - )" to enable auto activation slows down the prompt a lot. So is there actually any need to use it? I feel like auto activation is already achieved without running eval "$(pyenv virtualenv-init - )". Am I missing something?

The README says "some external tools (eg. jedi) might require you to activate the virtualenv environments":
https://github.com/pyenv/pyenv-virtualenv#activate-virtualenv
Is this the only reason to enable the auto activation?
Is the activation from pyenv virtualenv doing more than what the venv guide says - just some PATH modifications or changing where the shim points?

**Comment by yyuu** [comment]
With auto-activation (pyenv virtualenv-init) enabled, pyenv will try to mimic original activate script's behavior (e.g. 'VIRTUAL_ENV' in environ) as much as possible. Without it, pyenv will just switch the PATH for the version regardless if the version is a virtualenv or not.

Some kind of 3rd party tools are assuming that there's 'VIRTUAL_ENV' defined in environ if the current Python is a virtualenv. The auto-activation feature is for such kind of tools.

**Comment by haroldrandom** [comment]
any chance to speed up the showing time of prompt while enabling $(pyenv virtualenv-init - ) ?
