### ISSUE TITLE
pyenv-virtualenv: version `--no-error' is not a virtualenv

### ISSUE THREAD

**Issue by cmey** [pyenv/pyenv-virtualenv#208]
I get:

``pyenv-virtualenv: version `--no-error' is not a virtualenv``

printed in the terminal (just printed, `$?` is still `0`), anytime pyenv-virtualenv autoactivates a virtualenv.

Happens with `pyenv-virtualenv master (252d676)` (above error is displayed).
Does not happen with `pyenv-virtualenv tag v20151103` (no error displayed).

**Comment by blueyed** [comment]
How do you init it in your terminal?

**Comment by cmey** [comment]
I have in my `~/.bashrc`:
```
eval "$(~/.pyenv/bin/pyenv init -)"
eval "$(~/.pyenv/bin/pyenv virtualenv-init -)"
```

**Comment by blueyed** [comment]
There is nothing about `--no-error` in pyenv/pyenv-virtualenv.
Do you have a broken `.python-version` file somewhere, which would try to activate a version of that name?

Try `export PYENV_DEBUG=1` in your bashrc, and see what really triggers the error.

**Comment by cmey** [comment]
I've noticed that if I switch pyenv-virtualenv version (from master to v20151103, or vice versa) I get these messages:
`pyenv-virtualenv: version `--no-error' is not a virtualenv

but then, in a new terminal (does pyenv init again), it goes away (good).

I think it's fine, just need to re-init I guess.
