### ISSUE TITLE
python-config --prefix points to system instead of virtualenv's version

### ISSUE THREAD

**Issue by cmey** [pyenv/pyenv-virtualenv#209]
In an activated virtualenv:
```
pyenv versions
  system
  3.6.1
* software-3.6.1 (set by /Users/cmey/Code/GitHub/ButterflyNetwork/poseidon/software/.python-version)
```

On pyenv-virtualenv master (252d676):

`python-config --prefix`
`/System/Library/Frameworks/Python.framework/Versions/2.7`
(incorrect)

On pyenv-virtualenv tag v20151103:

`python-config --prefix`
`/Users/cmey/.pyenv/versions/3.6.1/Python.framework/Versions/3.6`
(correct)

**Comment by jimmywan** [comment]
Is your problem related to pyenv/pyenv-virtualenv#208

**Comment by cmey** [comment]
No, independent

**Comment by kersson** [comment]
Here is more information on this bug:

- Only seems to affect Python 3
- I did a `git bisect` and found c3d044d70a8d36188dd88f04f0be655475967871 to be the first bad commit

```
$ pyenv install 3.6.2
$ pyenv virtualenv 3.6.2 test-3.6.2
$ pyenv activate test-3.6.2
$ pyenv which python-config
/usr/bin/python-config
$ pyenv install 2.7.13
$ pyenv virtualenv 2.7.13 test-2.7.13
$ pyenv activate test-2.7.13
$ pyenv which python-config
/Users/kersson/.pyenv/versions/test-2.7.13/bin/python-config
```
Any way progress can be made on this bug? It's pretty serious.

**Comment by yyuu** [comment]
I suspect that this is testing the existence on wrong path; it should check the existence of `pyvenv.cfg` in the prefix, not in the `bin` inside the prefix.

https://github.com/pyenv/pyenv-virtualenv/blob/b4eb09d1dd3e619091e6c53f2b6ddb2ebbfd4e91/etc/pyenv.d/which/python-config.bash#L15
