### ISSUE TITLE
Add an option to automatically switch to virtualenv after creating it

### ISSUE THREAD

**Issue by nsw42** [pyenv/pyenv-virtualenv#210]
It would be great to add an option to `pyenv virtualenv` to allow the new virtualenv to be set as if I'd called `pyenv local`. This would make the behaviour closer to the original virtualenv.

Reasoning: When I `pyenv virtualenv` to create a new virtual environment, my mind instantly switches to that new environment. I then `pip install` several components, and only later realise that I've polluted my wider python version, requiring me to perform various tidy up.

**Comment by blueyed** [comment]
You can easily have your own wrapper script or shell function to call `pyenv activate …` afterwards.

As for me, I would not want to use `pyenv local`, but rather `pyenv shell` (and then `pyenv activate` improves this further).

btw: here is a wrapper script to create a temporary virtualenv: https://github.com/blueyed/dotfiles/blob/master/usr/bin/mktmpenv

**Comment by native-api** [comment]
Doubtfully a widely applicable improvement as per @blueyed 's reasoning, and there's been no support from other users since the original posting, either.
