### ISSUE TITLE
pyenv-virtualenv should not create new shims

### ISSUE THREAD

**Issue by Achimh3011** [pyenv/pyenv-virtualenv#211]
Hi,

I have a specific package that creates an executable (of the "console_script" persuasion). I so far had it in a virtualenv as it requires several packages I do not want to install globally. I could symlink the executable (to something like `~/usr/bin`) and upon running it would pick the right python version by virtue of the shebang line added.

When I create this virtualenv with pyenv however, a shim is created for the executable and my symlink is being masked - the command will only work if the right version is selected anyhow.

I can work around the problem by more fiddling with the PATH (making sure `~/usr/bin` is before the shims), but I think the more correct solution would be that creation of a package in a virtualenv should not create shims. 

Alternatively, one could make it configurable to suppress shim creation.

**Comment by blueyed** [comment]
Isn't the shim only created when you install your package in the virtualenv, and not when the virtualenv is created?

**Comment by Achimh3011** [comment]
You're right, I confused that. Still, is there a way to suppress shim creation?

**Comment by native-api** [comment]
Now that shims fall through to what's further on PATH if none of the selected versions have the shimmed executable, this problem should not be happening.
