### ISSUE TITLE
Fish 2.6.0 fixes setenv implementation, which breaks pyenv-virtualenv usage

### ISSUE THREAD

**Issue by daogilvie** [pyenv/pyenv-virtualenv#216]
This problem has already been fixed in regular pyenv head (but not the latest release 1.0.10), and is a simple change to use the `set -gx` command where there is currently `setenv`.

Symptom:
Script generated by `pyenv virtualenv init -`, when executed on fish 2.6.0, errors out with `setenv:` Too many arguments`

Confirmed on:
fish, version 2.6.0-63-g352cea16

Discussed here: fish-shell/fish-shell#4103

PR coming shortly

**Comment by blueyed** [comment]
#215 fixes this, but has failing tests.

**Comment by daogilvie** [comment]
Noted, apologies for timewasting. Will see if I can contribute along those lines, continuing under #215
