### ISSUE TITLE
New release for fish fixes

### ISSUE THREAD

**Issue by juraseg** [pyenv/pyenv-virtualenv#221]
Getting this issue when using pyenv-virtualenv from brew.

I see that this is fixed here: https://github.com/pyenv/pyenv-virtualenv/commit/862be21a32dd00236563c38e778842c29b61639d. But it's not yet released.

Just wondering when should we wait for this to be in released version?

**Comment by lucasb-eyer** [comment]
I guess this can be closed.

**Comment by yyuu** [comment]
https://github.com/pyenv/pyenv-virtualenv/releases/tag/v1.1.0 solved.
