### ISSUE TITLE
[Anaconda2-4.4.0] Run pip -> Error: Could not find an activated virtualenv

### ISSUE THREAD

**Issue by Xixiao007** [pyenv/pyenv-virtualenv#223]
Hi,

I use pyenv virtualenv. I Downloaded anaconda2-4.4.0 and initiated `deep-learning` virtual environment in arch Linux.

But after I activate `deep-learning` virual enviornment and  run `pip install`, the error `Could not find an activated virtualenv (required).` appears.

Command history is attached at end of this thread.

Please help, thanks!

Note:

1. I had a `readline` compiling warning when installing anaconda, but it was already resolved by following this https://github.com/pyenv/pyenv/issues/560  .  No other warning/error occurred during the installation or activation.
2. The `aws` vertual environment under python2.7.13 does not throw this error.

```bash
finxxi@archhome /home/finxxi [1]
> pyenv versions
* system (set by /home/finxxi/.pyenv/version)
  2.7.13
  2.7.13/envs/aws
  anaconda2-4.4.0
  anaconda2-4.4.0/envs/deep-learning
  aws
  deep-learning
finxxi@archhome /home/finxxi
> pyenv activate anaconda2-4.4.0/envs/deep-learning
finxxi@archhome /home/finxxi [deep-learning] 
> conda env list
# conda environments:
#
deep-learning         *  /home/finxxi/.pyenv/versions/anaconda2-4.4.0/envs/deep-learning
root                     /home/finxxi/.pyenv/versions/anaconda2-4.4.0
finxxi@archhome /home/finxxi [deep-learning] 
> python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> 
finxxi@archhome /home/finxxi [deep-learning] 
> pip install awscli
Could not find an activated virtualenv (required).

```

**Comment by blueyed** [comment]
Where is "Could not find an activated virtualenv (required)." coming from?
Does it look at `$VIRTUAL_ENV`?

**Comment by blueyed** [comment]
Is `$VIRTUAL_ENV` set also?

**Comment by blueyed** [comment]
You will have to grep / look at the source of `awscli` probably.

**Comment by yyuu** [comment]
I suspect some part of your environment set PIP_REQUIRE_VIRTUALENV in environment, and pip somehow failed to detect virtualenv activated by pyenv-virtualenv. I will have look in detail later.

**Comment by yyuu** [comment]
I confirmed that the message is shown only if `require_venv` is set and not running under virtualenv.

https://github.com/pypa/pip/blob/9.0.1/pip/basecommand.py#L208-L211

I also confirmed that `pip` is not seeing `VIRTUAL_ENV` to check if current runtime is virtualenv or not. (it's using `sys.real_prefix` or `sys.prefix != sys.base_prefix`)

https://github.com/pypa/pip/blob/9.0.1/pip/locations.py#L39-L49

`sys.prefix` and `sys.base_prefix` were same inside conda's environment created from miniconda3-4.3.11.

```
% ~/.pyenv/versions/miniconda3-4.3.11/envs/conda-env-test/bin/python
Python 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:09:58)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.prefix
'/home/yyuu/.pyenv/versions/miniconda3-4.3.11/envs/conda-env-test'
>>> sys.base_prefix
'/home/yyuu/.pyenv/versions/miniconda3-4.3.11/envs/conda-env-test'
>>> sys.real_prefix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'sys' has no attribute 'real_prefix'
```

`sys.real_prefix` and `sys.base_prefix` were not there inside conda's environment created from miniconda2-4.1.11.

```
% ~/.pyenv/versions/miniconda2-4.1.11/envs/conda-env-test2/bin/python
Python 2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:09:15)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import sys
>>> sys.prefix
'/home/yyuu/.pyenv/versions/miniconda2-4.1.11/envs/conda-env-test2'
>>> sys.base_prefix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'base_prefix'
>>> sys.real_prefix
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'real_prefix'
```

Because conda's environments are not actually a virtualenv, detecting them as a "non-virtualenv" itself could not be a problem. Possible workaround could be disable `require_venv` in `pip`.

**Comment by yyuu** [comment]
Please make sure you don't have `PIP_REQUIRE_VIRTUALENV=true` in your shell configurations.

Plus, some of your packages installed inside conda's environment may have custom shell profile script. Please make sure there's no `PIP_REQUIRE_VIRTUALENV` in `/home/finxxi/.pyenv/versions/anaconda2-4.4.0/envs/deep-learning/etc/conda/activate.d/*`.

https://github.com/pyenv/pyenv-virtualenv/blob/v1.1.0/bin/pyenv-sh-activate#L243-L245

**Comment by Xixiao007** [comment]
I was using fish shell and copied multiple settings from github.
There was a `PIP_REQUIRE_VIRTUALENV=true`, but comment it out doesn't eliminate the error. There must be other settings down in the rabbit hole as @yyuu said, which I couldn't verify easily.
In the end, I switch back to zsh, and the error is gone. 

Thanks for your guys quick response above!
