### ISSUE TITLE
zsh: command not found: pyenv

### ISSUE THREAD

**Issue by rghamilton3** [pyenv/pyenv-virtualenv#233]
My `.zshenv` contains 
```
export PYENV_ROOT="$HOME"/.pyenv
export PATH="$PYENV_ROOT"/bin:"$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
```
which works fine, however, if I simply add 
`eval "$(pyenv virtualenv-init -)"` 
I keep receiving the message 
`zsh: command not found: pyenv`

Pyenv and pyenv-virtualenv work perfectly fine and if I enter `exec "$SHELL"` the message goes away until I restart the terminal so I'm sure what the issue is.

I'm running Arch Linux, Zsh 5.4.2-1, tmux 2.5-3, termite 12-2, and the master branch of both pyenv and pyenv-virtualenv pulled today.

**Comment by yyuu** [comment]
It `eval "$(pyenv virtualenv-init -)"` is showing errors like "zsh: command not found: pyenv", it indicates that `pyenv-virtualenv-init` was called before `pyenv-init`. Since `pyenv-virtualenv` is heavily depending on `pyenv`, it needs to be initialized after `pyenv` has initialized.

Pasting your full zsh configurations (regard to pyenv/pyenv-virtualenv) here could help further investigation.

**Comment by dogfish182** [comment]
I have same issue

```
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
eval "$(pyenv virtualenv-init -)"
```

entire contents of my .zshenv and copy pasting it to a loaded shell works as intented.

**Comment by dichen001** [comment]
I have the same issue.
My `~/.zshenv` file:
```
export PYENV_ROOT="$HOME"/.pyenv
export PATH="$PYENV_ROOT"/bin:"$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
eval "$(pyenv virtualenv-init -)"
```

**Comment by pvarin** [comment]
My guess is that pyenv is being installed in a location that zsh doesn't use by default (like /usr/local/bin). You probably have a line at the top of your .zshrc that looks like `export PATH=$HOME/bin:/usr/local/bin:$PATH`. Moving that line to the top of your .zshenv might fix the problem for you.

**Comment by laike9m** [comment]
> My guess is that pyenv is being installed in a location that zsh doesn't use by default (like /usr/local/bin). You probably have a line at the top of your .zshrc that looks like `export PATH=$HOME/bin:/usr/local/bin:$PATH`. Moving that line to the top of your .zshenv might fix the problem for you.

Works for me, thanks :smile:

**Comment by Sphinxs** [comment]
Some update ?

**Comment by sean-smith** [comment]
I had this issue, after following https://github.com/pyenv/pyenv-installer

I changed my `~/.zshrc` from:

```bash
export PATH="~/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

To

```bash
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

**Comment by beizhengren** [comment]
> ```shell
> export PATH="$HOME/.pyenv/bin:$PATH"
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```

nice

**Comment by sean-smith** [comment]
Opened a PR to change this https://github.com/pyenv/pyenv-installer/pull/86

**Comment by NguyenThienLy** [comment]
> I had this issue, after following https://github.com/pyenv/pyenv-installer
> 
> I changed my `~/.zshrc` from:
> 
> ```shell
> export PATH="~/.pyenv/bin:$PATH"
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```
> 
> To
> 
> ```shell
> export PATH="$HOME/.pyenv/bin:$PATH"
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```

Cool, tk you verry much

**Comment by carusyte** [comment]
The above fix didn't work for me though. I used the following block in `~/.zshrc` instead:
```
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi
```

**Comment by iTosun** [comment]
i had also some difficulties in windows WSL2 & zsh on ubuntu 20.04 
I've removed the export command and that fixed it for me, now it looks like this at the end of my .zshrc
```
PATH="$HOME/.pyenv/bin:$PATH"     
if command -v pyenv 1>/dev/null 2>&1; then
   eval "$(pyenv init -)"                  
fi
 ```

**Comment by agoose77** [comment]
@andrewsiah what distro are you using?

pyenv recently changed how it loads the configuration. It requires the `PYENV_HOME` variable to be set, and `eval "$(pyenv init --path)"` to be run after you `export PATH="$PYENV_ROOT/bin:$PATH"`

**Comment by bytefluxio** [comment]
Found this issue after installing via the pyenv-installer. (zsh on wsl ubuntu running in conemu)
At first I added:
```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```
As mentioned in this thread. I got the following warning after restarting the shell:
```
WARNING: `pyenv init -` no longer sets PATH.
Run `pyenv init` to see the necessary changes to make to your configuration.
```
After running pyenv init, it pretty much told me to add `eval "$pyenv init --path)" before the `eval "$(pyenv init -)"` command. Which I did and now it works with the following:

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

However this means, that the pyenv-installer is currently broken. :(

**Comment by EM5813** [comment]
I've tried sto many variations and it's still not working. My current setup is 

```
export PATH="~/.pyenv/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
```
Still receiving **zsh: command not found: pyenv**

**Comment by CarlosChiarelli** [comment]
> export PYENV_ROOT="$HOME"/.pyenv
> export PATH="$PYENV_ROOT"/bin:"$PATH"
> if command -v pyenv 1>/dev/null 2>&1; then
>   eval "$(pyenv init -)"
> fi
> eval "$(pyenv virtualenv-init -)"

I'ts work! Thanks :D

**Comment by f4z3k4s** [comment]
In case of M1 users:

Pyenv gets installed to /opt/homebrew/Cellar/...

So running `pyenv which pyenv` showed me that I have pyenv installed to `/opt/homebrew/Cellar/pyenv/2.0.6/libexec/pyenv`.

Therefore, I added this to my `.zprofile`, before the eval pyenv part: 

`export PATH=$HOME/bin:/opt/homebrew/Cellar/pyenv/2.0.6/libexec:$PATH`

Works as expected.

**Comment by ScottGuthart** [comment]
> In case of M1 users:
> 
> Pyenv gets installed to /opt/homebrew/Cellar/...
> 
> So running `pyenv which pyenv` showed me that I have pyenv installed to `/opt/homebrew/Cellar/pyenv/2.0.6/libexec/pyenv`.
> 
> Therefore, I added this to my `.zprofile`:
> 
> `eval "$(/opt/homebrew/Cellar/pyenv/2.0.6/libexec/pyenv init --path)"` instead of `eval "$(pyenv init --path)"`
> 
> Works as expected.

This works for me too! But I wonder if we'll have to change this whenever pyenv updates?

**Comment by native-api** [comment]
Please see updated and hopefully clearer Pyenv shell setup instructions in https://github.com/pyenv/pyenv#readme
`eval "$(pyenv virtualenv-init -)"` should run in an rc file after `eval "$(pyenv init -)"` as before.

**Comment by native-api** [comment]
@ScottGuthart If you installed Pyenv with Homebrew, it should already be on PATH, in `$(brew --prefix)/bin`. If it's not, something is wrong with its installation.
It's also possible that you also have another version of Pyenv, installed from a Git checkout, that interferes with things. See https://github.com/pyenv/pyenv/issues/1760#issuecomment-932506432

**Comment by ScottGuthart** [comment]
@native-api gotcha, so maybe this is an issue just unique to me then. I don't think I've previously installed from git checkout but I did just migrate from an intel mac to an m1 mac, I'm guessing that's probably the cause of it somehow.

**Comment by earnestaddae** [comment]
> 

Thanks!

**Comment by YunoGas** [comment]
> I've tried so many variations and it's still not working. My current setup is
> 
> HELP!

Absolutely nothing helped me either. In my case , I had to say goodbye to anaconda . For some reason, the system refused to load anything other than python inside anaconda

**Comment by sinnrrr** [comment]
For those, who have installed pyenv with Homebrew and have `$(pyenv root)/bin` in the profile file, do the following:
1) `echo $(pyenv root)` in terminal and copy output (usually its `$HOME/.pyenv`
2) Replace `$(pyenv root)/bin` to **our output** (`$HOME/.pyenv/bin`)

**Comment by day0n** [comment]
> I had this issue, after following https://github.com/pyenv/pyenv-installer
> 
> I changed my `~/.zshrc` from:
> 
> ```shell
> export PATH="~/.pyenv/bin:$PATH"
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```
> 
> To
> 
> ```shell
> export PATH="$HOME/.pyenv/bin:$PATH"
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```
It works for me,I want to know why it works?

**Comment by native-api** [comment]
> It works for me,I want to know why it works?

`~` is not expanded within quotes.

**Comment by josephsfusco** [comment]
> ```shell
> export PATH="$HOME/.pyenv/bin:$PATH"
> ```

This worked for me as well, the key for me was putting putting it in ```~/.zshrc``` (not ```~/.zshenv```

**Comment by josephsfusco** [comment]
> I had this issue, after following https://github.com/pyenv/pyenv-installer
> 
> I changed my `~/.zshrc` from:
> 
> ```shell
> export PATH="~/.pyenv/bin:$PATH"
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```
> 
> To
> 
> ```shell
> export PATH="$HOME/.pyenv/bin:$PATH"
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```

This worked for me as well, the key for me was putting putting it in ```~/.zshrc``` (not ```~/.zshenv```

**Comment by bmasias1** [comment]
Currently im working on wsl2 with zsh, I change my `.zshrc` from:
```
export PATH=$HOME/bin:/usr/local/bin:$PATH`
```
To
```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
```

**Comment by juliusgabrielalba** [comment]
> I had this issue, after following https://github.com/pyenv/pyenv-installer
> 
> I changed my `~/.zshrc` from:
> 
> ```shell
> export PATH="~/.pyenv/bin:$PATH"
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```
> 
> To
> 
> ```shell
> export PATH="$HOME/.pyenv/bin:$PATH"
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```

worked like a charm ✨

**Comment by snakesgun** [comment]
This is my `.profile` and `.zprofile` settings which have solved the problem
 -  `.profile`
``` bash
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```

- `.zprofile`
``` bash
eval "$(/opt/homebrew/bin/brew shellenv)"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```

**Comment by yin-ori** [comment]
for me this setup made shell find pyenv, BUT the export path for python packages is still `opt/homebrew/lib/Python3.10` (which I don't even have installed anymore) for some reason. This also applies if I use the Mac standard Python (it will still download packages to the above path :S) 
Does anyone know how I can amend it? I've been trying to change it for weeks now with no success (on Mac OS Ventura M1) 
not sure if relevant ,but my `pyenv which pyenv` is `/opt/homebrew/Cellar/pyenv/2.3.12/libexec/pyenv`
and my pyenv virtual env is in this path: `/Users/<myusername>/.pyenv/versions/3.11.1`
```
.bash_profile
export PATH="/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

.bashrc is empty

.zprofile
# set PATH, MANPATH, etc., for Homebrew.
eval "$(/opt/homebrew/bin/brew shellenv)"

.zshrc
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
fi
```

would be awesome if someone could help!

**Comment by MoorAE** [comment]
this is my fix, i think for others like myself, it was a simple order of operation of the zsh; Order of reading startup files in zsh:
.zshenv → .zprofile → .zshrc → .zlogin
[](https://ss64.com/osx/syntax-profile.html)

so now my .zshenv and .zprofile look like this:

eval "$(/usr/local/bin/brew shellenv)"
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"

also i need to create a .zprofile and .zshenv (do the same instrustions for zprofile just swap zshenv)
[](https://www.insightsjava.com/2022/01/how-to-create-bash-profile-on-mac.html)

@yin-ori check your .zshenv

**Comment by BorjaDiago** [comment]
I had same issue and just follow the configuration steps posted here https://github.com/pyenv/pyenv#set-up-your-shell-environment-for-pyenv.

After make the necessary changes, the issue disappeared.
