### ISSUE TITLE
question: is this the correct tool if i want my virtualenv in my project dir?

### ISSUE THREAD

**Issue by cdaringe** [pyenv/pyenv-virtualenv#235]
hello:

thx for this tool.  i am using it successfully.  i would prefer to have my virtualenv live in my project dir.  im fairly new to python, so forgive me if it's a rookie q.

thx!

**Comment by keshavkaul** [comment]
Anyone know how to go about this? I'm coming from node and all project packages are installed locally under the `node_modules` folder inside the project directory.

**Comment by native-api** [comment]
For a project-centric rather than environment-centric approach, [Pipenv](https://pipenv.pypa.io/en/latest/) is likely a better fit.

Alternatively, you can symlink an independently created environment into `$(pyenv root)/versions`.
