### ISSUE TITLE
What am I doing wrong with .python-version?

### ISSUE THREAD

**Issue by humitos** [pyenv/pyenv-virtualenv#236]
I've using this `.python-version` file a lot in my old Xubuntu installation, then I switched to Archlinux and I copied all my config files and more.

Now, for some reason that I wasn't able to debug yet, this feature is not working anymore:

```
$ pyenv local
2.7.13/envs/mozio-ondemand
$ python
Python 3.6.2 (default, Jul 20 2017, 03:52:27) 
[GCC 7.1.1 20170630] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
$ cat .python-version 
2.7.13/envs/mozio-ondemand
```

So, what am I doing wrong and what else can I provide to help me debug this?

**Comment by pgrzesik** [comment]
Can you please provide result of `which python` and how your `$PATH` looks like ?
