### ISSUE TITLE
Document preferred method setting auto-activation in fish-shell on MacOS

### ISSUE THREAD

**Issue by vab9** [pyenv/pyenv-virtualenv#239]
The README specifies multiple ways to enable auto-activation for fish users:

_First, the instructions for fish users in general:_

Fish shell note: Add this to your ~/.config/fish/config.fish

status --is-interactive; and source (pyenv virtualenv-init -|psub)

_Then, later in the document:_

After installation, you'll still need to add
```
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```
to your profile (as stated in the caveats). You'll only ever have to do this once.

However, when using fish, the caveats actually read:

```
==> Caveats
To enable auto-activation add to your profile:
  if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
```

I have been using pyenv-virtualenv for a while now and it's been a great tool, but this was definitely a source of confusion for me when I first installed it (with Homebrew). So now I want to make sure new users don't get confused. If you tell me which command is preferred, I'd be happy to edit the README and open a pull request.

**Comment by Githeo** [comment]
Hello,

also if I add `status --is-interactive; and source (pyenv virtualenv-init -|psub)`  to the `~/.config/fish/config.fish` as written in the readme for a MacOs I get the following opening a new shell:

`Last login: Mon Nov 27 11:55:56 on ttys015
Unsupported use of '||'. In fish, please use 'COMMAND; or COMMAND'.
/var/folders/1c/db547_r97pvfmppsfyc1c85c0000gp/T//.psub.0d3H77No3m (line 6):     eval "$(pyenv sh-activate --quiet || pyenv sh-deactivate --quiet || true)" || true
                                                                                                                                                             ^
from sourcing file /var/folders/1c/db547_r97pvfmppsfyc1c85c0000gp/T//.psub.0d3H77No3m
	called on line 1 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

Welcome to fish, the friendly interactive shell`

**Comment by qpwo** [comment]
I am having this same issue

**Comment by fabianmoronzirfas** [comment]
+1

**Comment by fabiomcosta** [comment]
`status --is-interactive; and . (pyenv virtualenv-init -|psub)` worked for me.
Got that from: https://github.com/pyenv/pyenv/issues/32#issuecomment-68543034

**Comment by Ian-Liao** [comment]
Same here.

**Comment by native-api** [comment]
Please see updated and hopefully clearer Pyenv shell setup instructions in https://github.com/pyenv/pyenv#readme
`eval "$(pyenv virtualenv-init -)"` should run in an interactive shell after `eval "$(pyenv init -)"` as before.
