### ISSUE TITLE
I can not uninstall virtual environment.

### ISSUE THREAD

**Issue by woshihuangshuai** [pyenv/pyenv-virtualenv#240]
System: MacOS
When I use `pyenv uninstall venv_test`, it doesn't work and the virtual environment "venv_test" is still existed.

**Comment by jimmywan** [comment]
That's not what uninstall does. You're using the wrong command.

**Comment by woshihuangshuai** [comment]
@jimmywan I'm new to pyenv, can you tell me what is the right command？ Thank U very much！

**Comment by jimmywan** [comment]
Start with `pyenv help`

**Comment by thaning0** [comment]
`pyenv uninstall venv_test`
It does work, when you input `y` after this.
`pyenv-virtualenv: remove /Users/t/.pyenv/versions/3.7.1/envs/hello_world?`

Use `pyenv virtualenvs` to check.

**Comment by GustavoGama-Carlsberg** [comment]
> Start with `pyenv help`

For this kind of reply, please be stupid silently

**Comment by rola93** [comment]
Hey @chadjaros what is the difference between `pyenv uninstall my-virtual-env` and `pyenv virtualenv-delete my-virtual-env`? unfortunately, the [readme](https://github.com/pyenv/pyenv-virtualenv#delete-existing-virtualenv) in't clear enough in this point.

Thanks in advance
