### ISSUE TITLE
Latest version? 1.1.1 or 1.1.2?

### ISSUE THREAD

**Issue by ilovezfs** [pyenv/pyenv-virtualenv#264]
https://github.com/pyenv/pyenv-virtualenv/releases/latest has one opinion
https://github.com/pyenv/pyenv-virtualenv/releases has another

**Comment by ilovezfs** [comment]
@yyuu any idea what's happened here?

**Comment by yyuu** [comment]
Released v1.1.3 as the latest

**Comment by ilovezfs** [comment]
Thanks!
