### ISSUE TITLE
Why is prompt changing being removed? 

### ISSUE THREAD

**Issue by tadeoos** [pyenv/pyenv-virtualenv#268]
Hey,

according to current output: 
```
pyenv-virtualenv: prompt changing will be removed from future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior.
```

Can I ask how you came to this decision? I really like this feature

**Comment by pllim** [comment]
Had the same question. Went with https://github.com/pyenv/pyenv-virtualenv/issues/135#issuecomment-582180662 as my workaround.

**Comment by native-api** [comment]
@yyuu , since it was you who added the warning, could you comment?

My guess is that it's because Virtualenv themselves were going to do that.
...and IIRC already did it, so maybe we can proceed with the removal?

Would be nice to learn their rationale, too, of course...

**Comment by native-api** [comment]
> Pyenv-virtualenv makes virtualenvs behave like regular installations. The prompt changing removal was intended to erase the difference even further.

In which case, we can as well go the other way and _add_ printing of the active installation(s) to the prompt in the base Pyenv.
