### ISSUE TITLE
pyenv creating venv with wrong python version

### ISSUE THREAD

**Issue by Piplopp** [pyenv/pyenv-virtualenv#271]
Hello,
I'm trying pyenv and have some issues creating a virtualenv with the proper python version in it.

When I'm inside a venv and I try the `python --version` it always return the system version, not the one I created the venv with.

Here's what I did:

```
>pyenv versions
* system (set by /home/jerome/.pyenv/version)
  3.6.6
```

```
>pyenv virtualenv 3.6.6 testing
Looking in links: /tmp/tmpkare6ld0
Requirement already satisfied: setuptools in /home/jerome/.pyenv/versions/3.6.6/envs/testing/lib/python3.6/site-packages (39.0.1)
Requirement already satisfied: pip in /home/jerome/.pyenv/versions/3.6.6/envs/testing/lib/python3.6/site-packages (10.0.1)
```

```
>pyenv virtualenvs 
  3.6.6/envs/testing (created from /home/jerome/.pyenv/versions/3.6.6)
  testing (created from /home/jerome/.pyenv/versions/3.6.6)
```
I found an explaination in the doc for this so I guess it's normal
The next one is a bit weirder but why not
```
>pyenv versions
* system (set by /home/jerome/.pyenv/version)
  3.6.6
  3.6.6/envs/testing
  testing
```

So, when I go in the venv I just created and run `python --version` It returns the system version, not the one I created the venv with:
```
>pyenv activate testing 
pyenv-virtualenv: prompt changing will be removed from future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior.
>pyenv which python
/home/jerome/.pyenv/versions/testing/bin/python
>python --version
Python 3.5.3
```

Any idea what I'm missing ?

**Comment by Piplopp** [comment]
Solved it by using the .python-version file

**Comment by czy1996** [comment]
Hello, I'm facing  the same problem, what do you mean by using .python-version file? What i'm doing wrong?

**Comment by Piplopp** [comment]
I don't think I'll be of much help, but you can create a file `.python-version` that will be used to tell the virtualenv which python version you wanna use:

So basically I was doing `echo 3.6.6 > .python-version` in my project folder  and then I just created the venv with `pyenv virtualenv myenv` and it took the version I specified in the file.

I updated my pyenv recently and I can't reproduce my original issue, today the `pyenv virtualenv 3.6.6 myenv` works well on my machine.
