### ISSUE TITLE
pyenv-virtualenv: `3.6.5' is not installed in pyenv.

### ISSUE THREAD

**Issue by Mkone32** [pyenv/pyenv-virtualenv#277]
How to fix this?

**Comment by Mkone32** [comment]
meant 3.6.4

**Comment by AngeloLupo** [comment]
Run ```pyenv install 3.5.4``` before creating your virtualenv.

**Comment by abitofalchemy** [comment]
On macos, if one installs python3 using `brew install python3` and then have to re-install python3 using the command above, should I remove the macos python3 using `brew uninstall python3` since `pyenv` will now enable to pick and choose?
