### ISSUE TITLE
pyenv activate virtual_env_name works differently from source $VIRTUAL_ENV/bin/activate

### ISSUE THREAD

**Issue by hiphamster** [pyenv/pyenv-virtualenv#278]
Hi,
The major difference i see is that the PATH is only changed when i run 'source $VIRTUAL_ENV/bin/activate'. When i then start neovim, completions via deoplete-jedi only work if the PATH is changed.

New shell PATH:
➜  echo $PATH | awk -F':' '{for (i=1; i<NF; i++) { print $i }}'
/Users/alex/.plenv/shims
/Users/alex/.plenv/bin
/Applications/VirtualBox.app/Contents/MacOS
/opt/local/sbin
/opt/local/bin
/opt/neovim/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Applications/Wireshark.app/Contents/MacOS
/Users/alex/.pyenv/shims
/Users/alex/.pyenv/plugins/pyenv-virtualenv/shims
/Users/alex/.pyenv/bin
/usr/local/sbin

PATH after activating 'koala' virtualenv
[19:58:06|18-08-17][alex@Mac-mini]~/dev/koala
➜  pyenv activate koala
pyenv-virtualenv: prompt changing will be removed from future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior.
(koala) [19:58:14|18-08-17][alex@Mac-mini]~/dev/koala
➜  echo $PATH | awk -F':' '{for (i=1; i<NF; i++) { print $i }}'
/Users/alex/.plenv/shims
/Users/alex/.plenv/bin
/Applications/VirtualBox.app/Contents/MacOS
/opt/local/sbin
/opt/local/bin
/opt/neovim/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Applications/Wireshark.app/Contents/MacOS
/Users/alex/.pyenv/shims
/Users/alex/.pyenv/plugins/pyenv-virtualenv/shims
/Users/alex/.pyenv/bin
/usr/local/sbin
(koala) [19:58:23|18-08-17][alex@Mac-mini]~/dev/koala

PATH after running 'source $VIRTUAL_ENV/bin/activate'
  source $VIRTUAL_ENV/bin/activate
(koala) [19:59:57|18-08-17][alex@Mac-mini]~/dev/koala
➜  echo $PATH | awk -F':' '{for (i=1; i<NF; i++) { print $i }}'
/Users/alex/.pyenv/versions/3.6.5/envs/koala/bin
/Users/alex/.plenv/shims
/Users/alex/.plenv/bin
/Applications/VirtualBox.app/Contents/MacOS
/opt/local/sbin
/opt/local/bin
/opt/neovim/bin
/usr/local/bin
/usr/bin
/bin
/usr/sbin
/sbin
/Applications/Wireshark.app/Contents/MacOS
/Users/alex/.pyenv/shims
/Users/alex/.pyenv/plugins/pyenv-virtualenv/shims
/Users/alex/.pyenv/bin
/usr/local/sbin
(koala) [20:00:00|18-08-17][alex@Mac-mini]~/dev/koala

**Comment by blueyed** [comment]
Please fix the formatting, and point out the differences.

**Comment by blueyed** [comment]
From what I can tell it does not update $PATH, but relies on pyenv shims for the correct program to being used.

**Comment by blueyed** [comment]
I recommend using just pyenv maybe.
And look at https://github.com/pyenv/pyenv/pull/1185 maybe for better PATH handling.
