### ISSUE TITLE
How can I make prompt showing with activating virtualenv in fish

### ISSUE THREAD

**Issue by thanhngvpt** [pyenv/pyenv-virtualenv#284]
hi all.
I'm using fish shell and i want to show the name of activating virtual environment on the beginning of prompt such as `(env_name) user@machine ~/path...` but when activate virtual environment created by `python3 -m venv venv` then `source venv/bin/activate.fish` works as expected with prompt like this `(venv) user@machine ~/s/p/env>`. 
Many thanks.

**Comment by jvrn3** [comment]
I think I'm having the same problem as yours: How can i prompt (env_name) at Fish Shell?. 

I just opened an issue at pyenv, https://github.com/pyenv/pyenv/issues/1723.

**Comment by thanhngvpt** [comment]
Oh, sorry guys, this issue opened in long time, for now I think it works as expected, also describe clearly in the README. So i'll close this issue

**Comment by jvrn3** [comment]
I followed the instructions on README and I still get the problem.

**Comment by nostalgiaz** [comment]
same here!

**Comment by nrontsis** [comment]
This is not working, even after following `README`'s instructions.

`pyenv activate myenv` does not change the shell prompt, while
`source ~/.pyenv/versions/myenv/bin/activate.fish` does.

**Comment by halfdanrump** [comment]
I use an alias to do this, like this: 

```fish
# Aliases to active venvs
alias use_dev="source ~/.pyenv/versions/dev/bin/activate.fish"
```

**Comment by glennmatlin** [comment]
I believe the issue should be reopened -- followed the README and arrived at the same issues as others here

**Comment by caniko** [comment]
Maybe not necro-bump, but start a new thread? Just reference the older issues when creating your thread. Necro-bumping increases the cognitive load of projects.

**Comment by AthenaCaesura** [comment]
Has there been any progress on this? I'm totally new to fish, but for the others like me who stumble upon this thread I wrote a little function that can go right into your `config.fish` and more or less fixes this problem.

```fish
function set_local_venv
    source ~/.pyenv/versions/$argv/bin/activate.fish
end
```
So that you can just say `set_local_venv <your-venv-name>` and it appears just like other shells.
