### ISSUE TITLE
Why is virtualenv prefered over python -m venv?

### ISSUE THREAD

**Issue by LuckyType** [pyenv/pyenv-virtualenv#294]
I've just installed pyenv, pyenv-virtualenv and pyenvvirtualenvwrapper.

After setting everything up i noticed this warning:
`WARNING: the pyenv script is deprecated in favour of 'python3.6 -m venv'`

After checking the source code of /bin/pyenv-virtualenv it looks to me, that virtualenv is being prefered even tho the deprecation warning exists.
Am i missing something?
I think from Python 3.6 forward "python -m venv" should be the prefered way to go.

**Comment by yunusemrecan** [comment]
According to readme it does already. https://github.com/pyenv/pyenv-virtualenv#virtualenv-and-venv

**Comment by yyuu** [comment]
Yes

https://github.com/pyenv/pyenv-virtualenv/blob/v1.1.3/bin/pyenv-virtualenv#L555
