### ISSUE TITLE
system virtualenv created with python 2

### ISSUE THREAD

**Issue by caleb15** [pyenv/pyenv-virtualenv#323]
My system python version is 3.7.4 yet when the virtualenv is created it's from python 2.

```
# previously I tried running `pyenv virtualenv deploy` in the `fifteen5-deploy` folder

[oh-my-zsh] Random theme '/home/caleb/.oh-my-zsh/themes/gallifrey.zsh-theme' loaded...

caleb ~/Documents » pyenv global
system

caleb ~/Documents » pyenv versions

* system (set by /home/caleb/.pyenv/version)
  3.6.4
  3.6.4/envs/venv
  deploy
  venv

caleb ~ » pip freeze
ansible==2.7.10

caleb ~ » cd Documents 

caleb ~/Documents » cd fifteen5-deploy 

caleb Documents/fifteen5-deploy ‹master*› » pip freeze      
ansible==2.7.10 # this should not appear anymore

caleb Documents/fifteen5-deploy ‹master*› » cat .python-version
system

caleb Documents/fifteen5-deploy ‹master*› » pyenv virtualenvs
  3.6.4/envs/venv (created from /home/caleb/.pyenv/versions/3.6.4)
  deploy (created from /home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.16)
  venv (created from /home/caleb/.pyenv/versions/3.6.4)

caleb Documents/fifteen5-deploy ‹master*› » pyenv virtualenv-delete deploy
pyenv-virtualenv: remove /home/caleb/.pyenv/versions/deploy? y

caleb Documents/fifteen5-deploy ‹master*› » pyenv virtualenv system deploy
New python executable in /home/caleb/.pyenv/versions/deploy/bin/python
Installing setuptools, pip, wheel...
done.
Looking in links: /tmp/tmp8vdvY0
Requirement already satisfied: setuptools in /home/caleb/.pyenv/versions/deploy/lib/python2.7/site-packages (41.0.1)
Requirement already satisfied: pip in /home/caleb/.pyenv/versions/deploy/lib/python2.7/site-packages (19.2.1)

caleb Documents/fifteen5-deploy ‹master*› » pyenv virtualenvs             
  3.6.4/envs/venv (created from /home/caleb/.pyenv/versions/3.6.4)
  deploy (created from /home/linuxbrew/.linuxbrew/Cellar/python@2/2.7.16)
  venv (created from /home/caleb/.pyenv/versions/3.6.4)
```

I also tried making a virtualenv from my 3.6.4 version but that didn't work either.

What's wierd is the venv I created in another directory with 3.6.4 worked just fine. I don't know why it's not working now.

**Comment by caleb15** [comment]
```
caleb-H110M-A Documents/fifteen5-deploy ‹master*› » pyenv local 3.6.4                                                     2 ↵
caleb-H110M-A Documents/fifteen5-deploy ‹master*› » pyenv virtualenv deploy
Requirement already satisfied: setuptools in /home/caleb/.pyenv/versions/3.6.4/envs/deploy/lib/python3.6/site-packages
Requirement already satisfied: pip in /home/caleb/.pyenv/versions/3.6.4/envs/deploy/lib/python3.6/site-packages
caleb-H110M-A Documents/fifteen5-deploy ‹master*› » pip freeze | head
# shows libraries installed in the other 3.6.4 venv. Should show blank.
```

**Comment by caleb15** [comment]
> I don't remember why I installed python 3.7 via brew thinking

Ah, the reason python was installed via brew was that certain brew packages have python as a dependency, and brew installs python 3.7 for those packages instead of using the system python. Or at least it did when I tried installing `cheat` with brew.

**Comment by caleb15** [comment]
And for some reason pyenv thinks the homebrew python is my `system` python :thinking: odd...

**Comment by caleb15** [comment]
Not sure if this is a problem with `pyenv` or `pyenv-virtualenv`. I suppose I should raise a ticket with pyenv for wrong system labeling.

**Comment by caleb15** [comment]
I opened https://github.com/pyenv/pyenv/issues/1436

**Comment by wobo-aiguofer** [comment]
Hey, I was just running into some issues with my python and came back across this.

In your example you never activated the `deploy` virtualenv, so `pip freeze` will use whichever `pip` is active (I imagine in this case it's the `global` one). Generally, you'd probably want to set it locally for that directory using `pyenv local deploy`, but for the example you could run `PYENV_VERSION=deploy python --version` to see which version it's using.

Btw, the reason `pyenv` thinks your `system` python is the one from brew is due to your `$PATH`. Whichever python it finds first in `PATH` is the one that will be used for `system`.

**Comment by caleb15** [comment]
@wobo-aiguofer thanks, that clears up a lot. The only remaining thing I'm wondering about is why the virtualenv was created with python 2 even though the system python was python 3.

**Comment by caleb15** [comment]
I'm actually going to create a new issue cause this one got a bit cluttered.

**Comment by caleb15** [comment]
I created https://github.com/pyenv/pyenv-virtualenv/issues/344
