### ISSUE TITLE
Uninstalling pyenv-virtualenv gives message "pyenv: no such command `sh-activate'"

### ISSUE THREAD

**Issue by bvkin** [pyenv/pyenv-virtualenv#324]
On MacOs Mojave version 10.14.6 and zsh 5.3 (x86_64-apple-darwin18.0).

I've installed pyenv and pyenv-virtualenv via:
```
$brew install pyenv
$brew install pyenv-virtualenv
```

When uninstalling  pyenv-virtualenv via `$brew uninstall pyenv-virtualenv` I am consistently seeing the following message:

```
pyenv: no such command `sh-activate'
```

This appears after every command I enter into the terminal, not just things related to pyenv.

**Comment by briana-mcn** [comment]
Try exiting out of your terminal. I was running into the same issue until I killed the shell that I uninstalled pyenv-virtualenv in.

**Comment by bvkin** [comment]
Thanks! I managed to resolve it. Not sure exactly what it was but it seemed to go away after trying several times. Wouldn't be surprised if it was my terminal session.

**Comment by govindpatel** [comment]
can you look at .bashrc or .zshrc
