### ISSUE TITLE
Using pyenv "system" can cause PATH issues because it adds a system path to PATH

### ISSUE THREAD

**Issue by studgeek** [pyenv/pyenv-virtualenv#333]
I have noticed that using pyenv "system" can cause PATH issues for the running python program. This is because for "system" pyenv adds the python system path to PATH. So all the executables in that system path are overridden.

Here is an example:
User has the PATH "~/myjava:/usr/bin". In `~/my/java` is the executable `java`.
Their system python is at `/usr/bin/python`.
They have a script `dojavastuff.py` that runs calls "java".
They have pyenv set to "system".

If user runs `java` it runs `~/myjava/java`.
If user runs `/usr/bin/python dojavastuff.py` the script also runs `~/myjava/java`.
But, if user runs `python dojavastuff.py` the script runs `/usr/bin/java`. This is because pyenv has prefixed the path with `/usr/bin`.

This isn't a problem with non-system pyenvs because they only have the python executables. But with system, that prefixing overrides a lot more methods.

One possible fix might be for pyenv to create a `.pyenv/version/system` directory with links for the python executables. It would then  prefix `.pyenv/version/system` rather than `/usr/bin`. So, like non-system pyenvs, only the python executables would be added.

**Comment by caleb15** [comment]
It seems like this should be a issue for [pyenv](https://github.com/pyenv/pyenv), not python-virtualenv, no?

**Comment by studgeek** [comment]
I think this was fixed by https://github.com/pyenv/pyenv/pull/1169.
