### ISSUE TITLE
Pyenv doesn't change python version when activating / deactivating environment

### ISSUE THREAD

**Issue by tony-bony** [pyenv/pyenv-virtualenv#343]
I installed `pyenv-virtualenv` using linuxbrew on my Ubuntu 16.04 VPS. I am using `pyenv v1.2.16`. Now when I do:

```
pyenv install 3.8.1
pyenv virtualenv 3.8.1 test
cd /.pyenv/versions/3.8.1/envs/test
pyenv local 3.8.1
```

Then entering / leaving the ` /.pyenv/versions/3.8.1/envs/test` doesn't activate deactivate the virtualenv and I don't see `(test) username:~` in my shell.

Also when I activate virtualenv by hand `pyenv activate test` and then check the Python version, it prints the system Python version and not the one from environment:
```
python --version
Python 3.7.6
```
I can get the right Python version only by directly referring to virtualenv Python like this:
```
which python
/home/user/.pyenv/shims/python
/home/user/.pyenv/shims/python --version
Python 3.8.1
```
It does the same whenever the virtualenv "test" is activated or not.

Is this a pyenv bug? Or am I doing something wrong?
Can somebody help me?

**Comment by caleb15** [comment]
> cd /.pyenv/versions/3.8.1/envs/test

You don't need to cd into the directory that holds the virtualenv. 

From the readme:
> If eval "$(pyenv virtualenv-init -)" is configured in your shell, pyenv-virtualenv will automatically activate/deactivate virtualenvs on entering/leaving directories which contain a .python-version file that contains the name of a valid virtual environment as shown in the output of pyenv virtualenvs (e.g., venv34 or 3.4.3/envs/venv34 in example above) . .python-version files are used by pyenv to denote local Python versions and can be created and deleted with the pyenv local command.

**Comment by tony-bony** [comment]
@caleb15 Thanks. I also tried this with "normal" directories where my Python app is located but it didn't work as well. What am I missing? In [this stackoverflow](https://stackoverflow.com/questions/60212658/issues-with-pyenv-virtualenv-python-and-pip-not-changed-when-activating-deact) question i have put some more information...

**Comment by caleb15** [comment]
what is the output of `pyenv virtualenvs` in `/home/users/test`?
What are the contents of the `.python-version` file in `/home/users/test`?
Are you sure you have `eval "$(pyenv virtualenv-init -)"` configured in your shell? Is that line in your .bash_profile or .bashrc or .zshrc or whatever you are using?

**Comment by tony-bony** [comment]
I use `.profile` instead of `.bash_profile`. Is this OK?
I have put `eval "$(pyenv virtualenv-init -)"` in both.

```
env virtualenvs
  3.8.1/envs/composer (created from /home/user/.pyenv/versions/3.8.1)
  3.8.1/envs/demoapp (created from /home/user/.pyenv/versions/3.8.1)
  3.8.1/envs/test-3.8.1 (created from /home/user/.pyenv/versions/3.8.1)
  3.8.1/envs/venv_test (created from /home/user/.pyenv/versions/3.8.1)
  composer (created from /home/user/.pyenv/versions/3.8.1)
  demoapp (created from /home/user/.pyenv/versions/3.8.1)
  test-3.8.1 (created from /home/user/.pyenv/versions/3.8.1)
  venv_test (created from /home/user/.pyenv/versions/3.8.1)
```


```
vi .python-version 
3.8.1
```

```
vi ~/home/user/.bashrc
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

```
vi ~/home/user/.profile
export PATH="$HOME/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

**Comment by caleb15** [comment]
This is pretty unintuitive but I think the .python-version file has to match the _name_ of the venv, not the _version_. Try changing 3.8.1 in .python-version to `test`, cd'ing out of the dir and back in, and see if that works.

> If eval "$(pyenv virtualenv-init -)" is configured in your shell, pyenv-virtualenv will automatically activate/deactivate virtualenvs on entering/leaving directories which contain a .python-version file that contains the **name** of a valid virtual environment as shown in the output of pyenv virtualenvs (e.g., venv34 or 3.4.3/envs/venv34 in example above) . .python-version files are used by pyenv to denote local Python versions and can be created and deleted with the pyenv local command.

**Comment by tony-bony** [comment]
This is it. Thank you very much!

I just created the `.python-version` file with `pyenv local 3.8.1`  instead of using `pyenv local test`. I was simply confused by the word "version" which in `pyenv` refers to **name** of a virtualenv and not to Python **version**

**Comment by tony-bony** [comment]
There is no issue.
My problems were caused by incorrect usage of the `pyenv local` command (see last comment)

**Comment by tony-bony** [comment]
OK. The virtualenv is being now activated and deactivated but python version doesn't mach

```
(test) user@server:~/test$ python --version
Python 3.7.6
```
What am I missing?

**Comment by caleb15** [comment]
What are the contents of the `.python-version` file in the test dir?

**Comment by tony-bony** [comment]
The file `.python-version` contains only the name of virtualenv: "test"

**Comment by tony-bony** [comment]
@caleb15 Any clue what could be wrong with my installation? Why my Python version does not change when activating / deactivating a virtual environment?

**Comment by isaquealves** [comment]
Maybe your configuration is OK but it is not being actually used by bash. Did you try to reload your shell with `exec $SHELL` ?

**Comment by tony-bony** [comment]
Thanks for helping. 
Executing `exec $SHELL` changes indeed the Python version to 3.8.1. But it happens even without activating the virtual environment:
```
ssh user@xxxxxx.stratoserver.net
~$ python --version
Python 3.7.6
~$ exec $SHELL
~$ python --version
Python 3.8.1
```

Then entering / leaving the virtual environment directory doesn't change the Python version anymore. It remains 3.8.1

As far as I remember I installed Python 3.8.1 using linuxbrrew (homebrew) as cask.
Now when I do:

```
~$ brew list
autoconf  berkeley-db  bzip2  expat  gdbm  libbsd  libffi  m4  ncurses	openssl@1.1  patchelf  perl  pkg-config  pyenv	pyenv-virtualenv  python  python@2  readline  sqlite  xz  zlib
~$ brew search python
==> Formulae
app-engine-python  boost-python       boost-python3      gst-python         ipython            micropython        minimal-python     python ✔           python-dbus        python-markdown    python-yq          python@2 ✔         python@3.8         wxpython           zpython

If you meant "python" specifically:
It was migrated from homebrew/cask to homebrew/core.
```

Can this be of any importance?

**Comment by tony-bony** [comment]
The problem was that I had these two lines in my `.profile`
```bash
alias python=/home/linuxbrew/.linuxbrew/bin/python3
alias pip=/home/linuxbrew/.linuxbrew/bin/pip3
```

Now after removing these lines everything seems to work as expected:
```bash
user@server:~$ python --version
Python 2.7.17
user@server:~$ cd test
(test-3.8.1) user@server:~/test$ python --version
Python 3.8.1
(test-3.8.1) user@server:~/test$ cd ..
user@server:~$ python --version
Python 2.7.17
```
