### ISSUE TITLE
Custom pip.conf per virtualenv

### ISSUE THREAD

**Issue by ffissore** [pyenv/pyenv-virtualenv#366]
Hi all, and thank you for the amazing pyenv.

I would like to use a custom pip index with a specific virtualenv. We are using a custom pip registry (sonatype) and I've configured `~/.config/pip/pip.conf` accordingly.
When I use python for personal projects, I have to edit the config file and comment out the `index` entry.

Is there a way to have a pip.conf file which is specific to a virtualenv?

**Comment by ffissore** [comment]
It might be possible by creating a new `etc` folder for the virtualenv, and setting `PIP_CONFIG_FILE` to that path + `pip.conf`

**Comment by native-api** [comment]
According https://chadrick-kwag.net/adding-pip-config-file-in-virtualenv/ , you can simply put a `pip.conf` into the virtualenv directory. https://pip.pypa.io/en/stable/topics/configuration/#location confirms that.
