### ISSUE TITLE
Is <b>pyenv-virtualenv</b> internally dependent on virtualenv?

### ISSUE THREAD

**Issue by coderMR** [pyenv/pyenv-virtualenv#367]
Is <b>pyenv-virtualenv</b> internally dependent on <b>[virtualenv](https://pypi.org/project/virtualenv/)</b> project？
Or does <b>pyenv-virtualenv</b> implement a virtual environment of its own

**Comment by native-api** [comment]
Pyenv-virtualenv delegates to either Virtualenv or Venv depending on the options given and the virtual environment used. If Virtualenv is needed and not present for the active Python version, Pyenv-virtualenv installs it in some cases.
