### ISSUE TITLE
Can't activate virtualenv from Makefile

### ISSUE THREAD

**Issue by ammarasmro** [pyenv/pyenv-virtualenv#372]
Just trying to activate the environment from a Makefile

What I usually run
```bash
pyenv activate my_venv
```

The makefile I want to run instead
```bash
setup_environment:
    @echo "Activating virtual environment"
    @pyenv activate my_env
```

The output that I get
```
Activating virtual environment

Failed to activate virtualenv.

Perhaps pyenv-virtualenv has not been loaded into your shell properly.
Please restart current shell and try again.
```

I have added
```
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```
To
- `~/.zshrc`
- `~/.bashrc`
- `~/.bash_profile`

I'm using iTerm2 on a Mac so my focus is the first file but I tried editing the others cuz I thought Make might be invoking the command in a different way. No luck so far.

**Comment by cammil** [comment]
Have you tried something like this:

```
some-target:
	( \
	  source ~/.pyenv/versions/my_venv/bin/activate && \
	  run-something
	)
```

**Comment by ammarasmro** [comment]
Oh I think this works, thanks!
However this doesn't work on its own to activate the environment on the current console right?
```bash
some-target:
    source ~/.pyenv/versions/my_venv/bin/activate
```

**Comment by cammil** [comment]
I don't know for sure. I'm still fumbling about with make and shell stuff to be honest. I suspect it won't because I think make creates a separate subshell for each recipe (the indented line in your example). See here: https://www.gnu.org/software/make/manual/html_node/Execution.html#Execution

So once the recipe is completed, that subshell will be gone. I'm no expert though so this might not be completely accurate.

**Comment by ammarasmro** [comment]
The solution you suggested solves my problem so I'll just close this issue

Thanks again!

**Comment by 4F2E4A2E** [comment]
At least for me, the trick was top to escape the function call with an extra dollar sign, passing the pyenv initialization to the bash, instead of the Makefile runtime environment:

```bash
load-pyenv: 
	@eval "$$(pyenv init -)" && \
	pyenv activate ${PROJECT_NAME}
```
