### ISSUE TITLE
how to use pyenv-virtualenv on windows system

### ISSUE THREAD

**Issue by mossonli** [pyenv/pyenv-virtualenv#375]
how to use pyenv-virtualenv on windows system

**Comment by grabear** [comment]
+1

**Comment by calloftimereiver** [comment]
+1

**Comment by native-api** [comment]
Pyenv doesn't support Windows outside of WSL (which is Linux in a Hyper-V VM).

**Comment by cderv** [comment]
Pyenv is available on windows through https://github.com/pyenv-win/pyenv-win 

Does your answer means this is different project completely and all the plugin won't be supported there ?

**Comment by cderv** [comment]
yeah I should probably look there instead : https://github.com/pyenv-win/pyenv-win/issues/61

**Comment by native-api** [comment]
Pyenv-Win is a different project

**Comment by cderv** [comment]
I understand that now, it is not the same project but inspired project and logic. 

Though it seems this is the way to use a pyenv-like tool for python project on Windows as official pyenv as you said above works on Linux Distro on windows through WSL (which is different than main Windows). 

Having official support for Windows usage would be cool though, but I understand the design choices.
