### ISSUE TITLE
Python 2.7 get-pip.py needs a versioned link now

### ISSUE THREAD

**Issue by ursetto** [pyenv/pyenv-virtualenv#376]
It seems around January 2021 the unversioned `get-pip.py` became incompatible with Python 2.7.

```
Installing pip from https://bootstrap.pypa.io/get-pip.py...
Traceback (most recent call last):
  [...]
  File "/tmp/tmpLaSVe5/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
error: failed to install pip via get-pip.py
```

To fix this I think the 2.7 URL, `https://bootstrap.pypa.io/2.7/get-pip.py` needs to be added in the area below, just as in pyenv PR https://github.com/pyenv/pyenv/pull/1793 (commit https://github.com/pyenv/pyenv/commit/189afa88c65b6c524b9ccaf3e441b20f9ad7a000).

https://github.com/pyenv/pyenv-virtualenv/blob/294f64f76b6b7fbf1a22a4ebba7710faa75c21f7/bin/pyenv-virtualenv#L482

**Comment by Littelarch** [comment]
Hello. I think I may meet some problem related to this "get-pip.py" problem. I can't create virtualenv with python 2.x. I tried both the python2.7 of system and the python2.7 installed by pyenv but both failed.

Error message is like below:

```
>>> pyenv virtualenv 2.7.18 test2718

......(skip some message of "Requirement already satisfied")

created virtual environment CPython2.7.17.final.0-64 in 466ms
  creator CPython2Posix(dest=/home/arch/.pyenv/versions/2.7.18/envs/test2718, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, wheel=bundle, setuptools=bundle, via=copy, app_data_dir=/home/arch/.local/share/virtualenv)
    added seed packages: pip==20.3.4, setuptools==44.1.1, wheel==0.36.2
  activators PythonActivator,CShellActivator,FishActivator,PowerShellActivator,BashActivator
ensurepip is disabled in Debian/Ubuntu for the system python.

Python modules For the system python are usually handled by dpkg and apt-get.

    apt-get install python-<module name>

Install the python-pip package to use pip itself.  Using pip together
with the system python might have unexpected results for any system installed
module, so use it on your own risk, or make sure to only use it in virtual
environments.

Installing pip from https://bootstrap.pypa.io/get-pip.py...
ERROR: This script does not work on Python 2.7 The minimum supported Python version is 3.6. Please use https://bootstrap.pypa.io/2.7/get-pip.py instead.
error: failed to install pip via get-pip.py
```

I'm using ubuntu18 and installed pyenv by pyenv-installer today. And I installed pip by "sudo apt install python-pip". Did I miss something which made this problem?

**Comment by melaanya** [comment]
The same problem as for @Littelarch happens to me in Ubuntu 20

**Comment by melaanya** [comment]
For me the problem was solved after installing `more-itertools==5.0.0` instead of 8.0 that was there (in the local environment of 2.7.18)

**Comment by jkbhagatio** [comment]
I am getting the same issue as @Littelarch when trying to create a 2.7 virtual env with pyenv, and @ursetto 's proposed solution of adding the 2.7 URL as one of the cases in the `pyenv-virtualenv` file worked for me

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv-virtualenv/pull/403
