### ISSUE TITLE
fish function _pyenv_virtualenv_hook clutters /tmp

### ISSUE THREAD

**Issue by marcusatiliusregulus** [pyenv/pyenv-virtualenv#379]
in fish every time _pyenv_virtualenv_hook runs, which is everytime the prompt is redrawn - so quite often, a new file called .psub.<random-string> is created with the content "false" in /tmp.

these files stay there until reboot or whenever else /tmp is cleared and if youre working in the terminal you dont have to wait long for them to reach numbers in the hundreds!

**Comment by marcusatiliusregulus** [comment]
i think the problem lies in the use of `source (command | psub)` instead of `command | source` as fish-shell's @faho pointet out. [link](https://matrix.to/#/!YLTeaulxSDauOOxBoR:matrix.org/$PKzq-jiee2s-GtM_aZI44H6V2_JIKwWSbuStlyhx6_U?via=gitter.im&via=matrix.org&via=govanify.com) to conversation on matrix/gitter

**Comment by faho** [comment]
Note: While it is cleaner and recommended to use `command | source`, the underlying issue is https://github.com/fish-shell/fish-shell/issues/7792, which I've just fixed.
