### ISSUE TITLE
`colorize` not available in shell and not included in installation instructions

### ISSUE THREAD

**Issue by drydenb** [pyenv/pyenv-virtualenv#381]
Hey there! 

In the `pyenv-virtualenv` script, there is a reference to a command called `colorize` [here]( https://github.com/pyenv/pyenv-virtualenv/blob/294f64f76b6b7fbf1a22a4ebba7710faa75c21f7/bin/pyenv-virtualenv#L472).

To my knowledge, this command is not installed in most shells, and I wasn't able to find instructions in the README on how to install this dependency, or what version that dependency should be.

Could anyone shed some light on this dependency? Of course, the workaround is to not set `PIP_VERSION` and avoid the code block entirely, but currently it looks like this code can break after running the pyenv-installer in most shells if this env var is set.

**Comment by austinpray-mixpanel** [comment]
Furthermore, I get 

```
colorize: foreground color '1' cannot be made of non-alphabetic characters
```

even with `colorize/focal,now 0.64-1 amd64` on ubuntu 20.04

**Comment by native-api** [comment]
`colorize` is a shell function defined in `python-build`. Its use here is indeed a mistake. It needs to either be removed or copies over from there.
