### ISSUE TITLE
Warning about the load path tells the user to append to `~/.bash_profile` which makes `~/.profile` not run

### ISSUE THREAD

**Issue by jack1142** [pyenv/pyenv-virtualenv#383]
Currently, this is the warning message you get from pyenv installer after installation (the part that concerns this issue is from `pyenv-virtualenv` and is at the end of this code block):
```
WARNING: seems you still have not added 'pyenv' to the load path.

# Add pyenv executable to PATH by adding
 the following to ~/.profile:

export PATH="/home/vm/.pyenv/bin:$PATH"
# Load pyenv automatically by appending
# the following to ~/.bashrc:

eval "$(pyenv init -)"

# And the following to ~/.profile

eval "$(pyenv init --path)"

# Make sure to restart your entire logon session
# for changes to ~/.profile to take effect.

# Load pyenv-virtualenv automatically by adding
# the following to ~/.bash_profile:

eval "$(pyenv virtualenv-init -)"

```

This leads to a situation where the user will have both `~/.profile` and `~/.bash_profile` which in turn causes `~/.profile` to not be run at all and therefore making the PATH change in `~/.profile` not actually run (and that means everything else simply doesn't work).

From bash(1) manual (emphasis mine):
> When bash is invoked as an interactive login shell, or as a non-interactive shell with the --login option, it first reads and executes commands from the file /etc/profile, if that file exists. After reading that file, it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, **and reads and executes commands from the first one that exists and is readable**. The --noprofile option may be used when the shell is started to inhibit this behavior.

**Comment by jack1142** [comment]
It does seem that a preferred way would be to use the same file for *all these commands* as the commands from `.bashrc` are likely to run *before* the ones from `.profile` as usually `.profile` sources `.bashrc` at the beginning.

**Comment by native-api** [comment]
@anton-petrov I warned you about that in https://github.com/pyenv/pyenv-installer/pull/109#issue-631638610 !

**Comment by anton-petrov** [comment]
Fixed https://github.com/pyenv/pyenv-virtualenv/commit/8c7ef734f9689739a9787b2e40f6f63b26918d79

**Comment by jack1142** [comment]
While the issue from the title is resolved, the one I mentioned in the second comment isn't.

Currently, when following instructions, users would add these lines to the end of `.bashrc`:
```
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```
And these lines to the end of `.profile`:
```
export PATH="/home/vm/.pyenv/bin:$PATH"
eval "$(pyenv init --path)"
```
which leads to a situation where `pyenv` commands are ran *before* `pyenv` is a part of the `PATH`.

This wasn't an issue before as pyenv-installer told users to put all of the lines in `.bashrc`.

Should I make a separate issue for this?

**Comment by native-api** [comment]
See https://github.com/pyenv/pyenv/issues/1909#issuecomment-835849900
