### ISSUE TITLE
Getting "Failed to activate virtualenv" when using with pyenv 2.0.0-rc1-2-gac4de222 (cloned on 2021-05-22)

### ISSUE THREAD

**Issue by renatocan** [pyenv/pyenv-virtualenv#387]
I tried update pyenv but I'm getting an error when trying to use pyenv-virtualenv:

```
Failed to activate virtualenv.

Perhaps pyenv-virtualenv has not been loaded into your shell properly.
Please restart current shell and try again.
```
I'm using zsh.

Steps to reproduce:

* Clone pyenv:

```
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
```

* Add config to ~/.zshrc:

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
export WORKON_HOME=$HOME/.virtualenvs
export PROJECT_HOME=$HOME/repo/prj
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init --path)"
fi
```
* Restart shell and clone pyenv-virtualenv:

```
git clone https://github.com/pyenv/pyenv-virtualenv.git $(pyenv root)/plugins/pyenv-virtualenv
```

* Add pyenv-virtualenv config to ~/.zshrc:
```
eval "$(pyenv virtualenv-init -)"
```

* Restart shell and install a Python version:

```
pyenv install 3.9.5
```

* Create a virtualenv:

```
pyenv virtualenv 3.9.5 py3
```

Try to activate it:

```
pyenv activate py3
```

When using pyenv 1.2.26, the problem does not occur (in that case, we must initialize pyenv using `pyenv init -` instead of `pyenv init --path`).

**Comment by arg0user** [comment]
I am experiencing the same issue:  pyenv-virtualenv installed with homebrew.  It seems to initialize ok, shows the default virtual env command promp (set via ~/.pyenv/version), but then has problems with the activate parameter.

I tried:
```
brew reinstall pyenv-virtualenv
```

and noticed no differences.

Error message while trying to activate:
```
Failed to activate virtualenv.

Perhaps pyenv-virtualenv has not been loaded into your shell properly.
Please restart current shell and try again.
```

**Comment by jbub** [comment]
This fixed my zsh setup:

.zprofile

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
```

.zshrc

```
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

**Comment by arg0user** [comment]
Good post.  Confirming that on latest pyenv homebrew (pyenv 2.0.0.0), if you eval pyenv with --path, and then -, it seems to be happier:
```
eval "$(pyenv init --path)"
```
then:
```
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

**Comment by renatocan** [comment]
Thank you. Confirming that if we eval pyenv with --path, and then - on `~/.zshrc`, it works:

```
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

**Comment by modonovan** [comment]
> Good post. Confirming that on latest pyenv homebrew (pyenv 2.0.0.0), if you eval pyenv with --path, and then -, it seems to be happier:
> 
> ```
> eval "$(pyenv init --path)"
> ```
> 
> then:
> 
> ```
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```

Confirming that this was the fix for me when running MacOS BigSur / iTerm2 / Zsh

**Comment by modonovan** [comment]
> Thank you. Confirming that if we eval pyenv with --path, and then - on `~/.zshrc`, it works:
> 
> ```
> eval "$(pyenv init --path)"
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```

Confirming that this was the fix for me when running MacOS BigSur / iTerm2 / Zsh

**Comment by smkbarbosa** [comment]
> eval "$(pyenv init --path)"
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"

Confirm that this was the fix for me when running Debian / Zsh

**Comment by peter0083** [comment]
> Thank you. Confirming that if we eval pyenv with --path, and then - on `~/.zshrc`, it works:
> 
> ```
> eval "$(pyenv init --path)"
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```

confirmed that this worked well for me for my `~/.profile` when running Ubuntu 20.04 LTS / Bash

**Comment by paluigi** [comment]
This fixed my issue as well on Ubuntu 20.04 LTS . Added to .bashrc

**Comment by nicholasovunda** [comment]
> eval "$(pyenv virtualenv-init -)"

This worked for me.

**Comment by wmuengineer** [comment]
This fix also works for Iterm2, Zsh, Pycharm on MacOS Ventura


> > Thank you. Confirming that if we eval pyenv with --path, and then - on `~/.zshrc`, it works:
> > ```
> > eval "$(pyenv init --path)"
> > eval "$(pyenv init -)"
> > eval "$(pyenv virtualenv-init -)"
> > ```
> 
> Confirming that this was the fix for me when running MacOS BigSur / iTerm2 / Zsh

**Comment by petersongeiger** [comment]
Also, it worked for me after added ---> eval "$(pyenv init -)" that was missing

Worked:
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

**Comment by oge1ata** [comment]
Confirming that the below worked for me on my kali linux system using zsh as bash is no more use since 2020:

eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

**Comment by elizaMathaai** [comment]
> This fix also works for Iterm2, Zsh, Pycharm on MacOS Ventura
> 
> > > Thank you. Confirming that if we eval pyenv with --path, and then - on `~/.zshrc`, it works:
> > > ```
> > > eval "$(pyenv init --path)"
> > > eval "$(pyenv init -)"
> > > eval "$(pyenv virtualenv-init -)"
> > > ```
> > 
> > 
> > Confirming that this was the fix for me when running MacOS BigSur / iTerm2 / Zsh

This fixed my issue in MacOS Sonoma

**Comment by MichaelEjila** [comment]
> Thank you. Confirming that if we eval pyenv with --path, and then - on `~/.zshrc`, it works:
> 
> ```
> eval "$(pyenv init --path)"
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```

Confirming this was the fix on my Sonoma

**Comment by newTypeGeek** [comment]
> > Thank you. Confirming that if we eval pyenv with --path, and then - on `~/.zshrc`, it works:
> > ```
> > eval "$(pyenv init --path)"
> > eval "$(pyenv init -)"
> > eval "$(pyenv virtualenv-init -)"
> > ```
> 
> Confirming this was the fix on my Sonoma

Thanks, it works on macOS Sonoma

**Comment by EddyDavies** [comment]
I have gone for this, don't get the error but yet to see if it works when it should

```
# Initialize pyenv if it exists
if command -v pyenv >/dev/null 2>&1; then
  eval "$(pyenv init --path)"
  eval "$(pyenv init -)"
fi

# Initialize pyenv-virtualenv if it exists
if command -v pyenv >/dev/null 2>&1 && pyenv commands | grep -q 'virtualenv-init'; then
  eval "$(pyenv virtualenv-init -)"
fi
```

**Comment by EbodShojaei** [comment]
Thank you! Confirming this works on pyenv version 2.5.3 and virtualenv version 1.2.4 on Mac M2 Silicon Sequoia 15.3.1 👌

> Thank you. Confirming that if we eval pyenv with --path, and then - on `~/.zshrc`, it works:
> 
> ```
> eval "$(pyenv init --path)"
> eval "$(pyenv init -)"
> eval "$(pyenv virtualenv-init -)"
> ```

**Comment by AryavT** [comment]
Fixed my. issue also by doing following on Mac Sequoia 15.3  
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
