### ISSUE TITLE
Virtualenv created under .penv instead of .pyenv

### ISSUE THREAD

**Issue by aabanaag** [pyenv/pyenv-virtualenv#399]
I installed poetry but I don't think that is directly related to this, when I created a virtualenv using `pyenv virtualenv` command it is created under `.penv` instead of `.pyenv` folder. Now no matter what I do under pycharm I can't find the virtualenv under existing environment. Any ideas?

<img width="555" alt="Screen Shot 2021-07-31 at 11 54 35 PM" src="https://user-images.githubusercontent.com/2245822/127745438-b439cfc5-c6ad-42e9-a4db-5e9d580f1285.png">

**Comment by native-api** [comment]
Check your `PYENV_ROOT` envvar. You probably made a typo when configuring it.

**Comment by aabanaag** [comment]
ohh, nice catch. thank you
