### ISSUE TITLE
pyenv virtualenv activate doesn't change $PATH

### ISSUE THREAD

**Issue by mprat** [pyenv/pyenv-virtualenv#407]
System: 
* Ubuntu 20.04, fresh install
* pyenv installed with https://github.com/pyenv/pyenv-installer
* using bash shell. the only place pyenv configurations are stored is in `.bash_profile` with these lines at the bottom:

```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init --path)"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

I created a virtual environment with the following:

```
pyenv install 3.9.7
pyenv virtualenv 3.9.7 testenv
```

Now when I try to activate the virtualenv with `pyenv activate testenv`, I get the following:

```
[mprat@europa] $ pyenv activate testenv
(testenv) [mprat@europa] $ which python
/home/mprat/.pyenv/shims/python
(testenv) [mprat@europa] $ echo $PATH
/home/mprat/gems/bin:/home/mprat/.pyenv/plugins/pyenv-virtualenv/shims:/home/mprat/.pyenv/shims:/home/mprat/.pyenv/bin:/home/mprat/gems/bin:/home/mprat/.local/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

It is clear that the `$PATH` variable that dictates which python version is running in my virtualenv was not sourced. Manually running `source ~/.pyenv/versions/testenv/bin/activate` shows the output of `echo $PATH` to be: 

```
/home/mprat/.pyenv/versions/3.9.7/envs/tf/bin:/home/mprat/gems/bin:/home/mprat/.pyenv/plugins/pyenv-virtualenv/shims:/home/mprat/.pyenv/shims:/home/mprat/.pyenv/bin:/home/mprat/gems/bin:/home/mprat/.local/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
```

which means running `which python` yields the expected result:

```
(testenv) [mprat@europa] $ which python
/home/mprat/.pyenv/versions/3.9.7/envs/testenv/bin/python
```

Why it is that `pyenv activate XXXX` doesn't change the `$PATH` variable (and seemingly doesn't run the appropriate `activate` script)?

**Comment by zhao-weiqi** [comment]
same problem for me.

**Comment by kzim44** [comment]
Had the same problem on macOS. This solved it for me - https://github.com/pyenv/pyenv-virtualenv/issues/390#issuecomment-852599456

**Comment by native-api** [comment]
Please see updated and hopefully clearer Pyenv shell setup instructions in https://github.com/pyenv/pyenv#readme
`eval "$(pyenv virtualenv-init -)"` should run in an rc file after `eval "$(pyenv init -)"` as before.
