### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by anylayer** [pyenv/pyenv-virtualenv#417]
BUILD FAILED (Ubuntu 21.10 using python-build 2.2.3-4-g971397dd)
![image](https://user-images.githubusercontent.com/46556817/149366530-4b3a479f-d3b3-4860-8d89-aa6b122c0cf5.png)

**Comment by native-api** [comment]
Please add the required disgnostic data per issue template.

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv-virtualenv/issues/410#issuecomment-945190616
We cannot diagnose segfaults for you. Usually, that means that some of the dynamically loaded libs are incompatible.
