### ISSUE TITLE
Hook for pyenv activate 

### ISSUE THREAD

**Issue by danfrankj** [pyenv/pyenv-virtualenv#428]
I would like to be able to add a hook script when pyenv activate runs. In particular it would be helpful for me to be able to modify some environment vars. 

It appears that some commands have such hooks: https://github.com/pyenv/pyenv-virtualenv/blob/master/bin/pyenv-virtualenv#L515 

Let me know if you'd be open to adding such functionality to `activate`. Happy to create a PR if so

See also: https://github.com/pyenv/pyenv/issues/2337

Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [X] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [X] Make sure no duplicated issue has already been reported in [the pyenv-virtualenv issues](https://github.com/pyenv/pyenv-virtualenv/issues). You should look in closed issues, too.
* [X] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [X] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [X] Make sure your problem is not derived from other plugins.
  * This repository is maintaining the `pyenv-virtualenv` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [ ] Platform information (e.g. Ubuntu Linux 20.04):
- [ ] OS architecture (e.g. amd64):
- [ ] pyenv version:
- [ ] pyenv-virtualenv version:
- [ ] Python version:
- [ ] virtualenv version (if installed):
- [ ] Please attach the debug log of a faulty Pyenv invocation as a gist
  * If the problem happens in a Pyenv invocation, you can turn on debug logging by setting `PYENV_DEBUG=1`, e.g. `env PYENV_DEBUG=1 pyenv install -v 3.6.4`
  * If the problem happens outside of a Pyenv invocation, get the debug log like this:
     ```
     export PS4='+(${BASH_SOURCE}:${LINENO}): ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
     set -x
     <reproduce the problem>
     set +x
     ```

**Comment by native-api** [comment]
@yyuu has approved it in https://github.com/pyenv/pyenv/issues/2337#issuecomment-1107797056.
I trust his judgement so no objections from me, either.

Go ahead but do heed his warnings about possible side effects -- in particular, think carefully where exactly to insert the call point so that it's potentially useful for more use cases than just yours and how to name the hook executables to avoid confusion.
