### ISSUE TITLE
python3-config (along with other tools) does not respect the version virtualenv hook on

### ISSUE THREAD

**Issue by favrei** [pyenv/pyenv-virtualenv#459]
Hello, thanks for building/maintaining the essential python tool for the community, appreciated!

Recently, I have a problem with the python3-config command when I activate a virtual environment based on python 3.11.4 (well, in fact this problem stays whatever the version I swiched).

The problem is that pyenv which python3-config returns the system path (/usr/bin/python3-config) instead of the pyenv path (/home/pete/.pyenv/versions/a/bin/python3-config). This causes issues when I try to compile some packages that depend on python3-config.

```
pete@pop-os:~$ pyenv --version
pyenv 2.3.20-1-gd0b78fd5

pete@pop-os:~$ pyenv virtualenv --version
pyenv-virtualenv 1.2.1 (python3.11 -m venv)

pete@pop-os:~$ pyenv global 3.11.4

pete@pop-os:~$ pyenv which python3
/home/pete/.pyenv/versions/3.11.4/bin/python3

pete@pop-os:~$ pyenv which python3-config
/home/pete/.pyenv/versions/3.11.4/bin/python3-config

pete@pop-os:~$ pyenv activate a  # A is a virtual environment based on python 3.11.4

(a) pete@pop-os:~$ pyenv which python3

/home/pete/.pyenv/versions/a/bin/python3

(a) pete@pop-os:~$ pyenv which python3-config

/usr/bin/python3-config  # expected to be the one hosted by pyenv not from system

```

System Information:
```
Pop!_OS 22.04 LTS
pyenv 2.3.20-1-gd0b78fd5
pyenv-virtualenv 1.2.1 (python3.11 -m venv)
python 3.11.4
```

Initialization in my .bashrc:
```
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"
```

Please let me know what additional information I can provide.
Thanks

**Comment by native-api** [comment]
Both `venv` and `virtualenv` deliberately omit creating links to `python-config` for some reason. [Virtualenv even deliberately dropped this feature in order to copy Venv](https://github.com/pypa/virtualenv/issues/1808).

**Comment by native-api** [comment]
@carljm could you possibly enlighten us on the rationale for not including `python-config` (as well as `pydoc`) into the list executables linked into a venv as per https://peps.python.org/pep-0405/ ?

**Comment by carljm** [comment]
I don't remember, and there's no indication in the PEP text that it was a deliberate omission. If you believe it should be added, the right course of action is to file an issue on CPython and make a case for it.

**Comment by native-api** [comment]
@carljm Thank you!

If there's no specific reason for omission, we'll do that, add in the meantime, be adding it in Pyenv, too.

**Comment by favrei** [comment]
hey, thank you for the information.
Are you going to create a dedicated issue and close this one? Or you are planning to keep current issue? Both work for me.

**Comment by native-api** [comment]
We'll keep this one.
