### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by joshfrench** [pyenv/pyenv-virtualenv#463]
Any chance for a new release soon? I've been running my fork for #452 locally, would love to get back on the standard path for updates. Thanks!

**Comment by native-api** [comment]
https://github.com/pyenv/pyenv-virtualenv/releases/tag/v1.2.2

**Comment by native-api** [comment]
You can install the HEAD version with Homebrew with `--head`, no need to wait for a release.

**Comment by joshfrench** [comment]
Thank you!
