### ISSUE TITLE
Latest version

### ISSUE THREAD

**Issue by ghost** [pyenv/pyenv-virtualenv#464]
Why GitHub homepage says the last version is 1.2.1:

![image](https://github.com/pyenv/pyenv-virtualenv/assets/118444583/45154798-314e-424e-9be3-3e6483443fbe)

When in fact [it is 1.2.2](https://github.com/pyenv/pyenv-virtualenv/releases/tag/v1.2.2)?

**Comment by chrisolof** [comment]
Also just noticed that when you switch to v1.2.2, `pyenv virtualenv --version` still reports 1.2.1 (looks like [this line](https://github.com/pyenv/pyenv-virtualenv/blob/v1.2.2/bin/pyenv-virtualenv#L16) may be the issue).
