### ISSUE TITLE
Incorrect version reported by `pyenv virtualenv --version`

### ISSUE THREAD

**Issue by darkfishy** [pyenv/pyenv-virtualenv#465]
### Description

`pyenv virtualenv --version` from release `1.2.2` incorrectly reports self version as `1.2.1`.

This is a packaging issue. Last time self version was updated in https://github.com/pyenv/pyenv-virtualenv/pull/449/commits/7a6ea242718bfddf9fbed34f670a9ac836f758d4, however, since then `1.2.2` package has been released.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv-virtualenv issues](https://github.com/pyenv/pyenv-virtualenv/issues). You should look in closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from other plugins.
  * This repository is maintaining the `pyenv-virtualenv` plugin only. Please refrain from reporting issues of other plugins here.

**Comment by ushuz** [comment]
Fixed in #471
