### ISSUE TITLE
Don't use `.python-version` for auto-activation

### ISSUE THREAD

**Issue by krystof-k** [pyenv/pyenv-virtualenv#472]
Too many issues will kill our team's development velocity, drastically.
Make sure you have checked all steps below.

### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv-virtualenv issues](https://github.com/pyenv/pyenv-virtualenv/issues). You should look in closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from other plugins.
  * This repository is maintaining the `pyenv-virtualenv` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information (e.g. Ubuntu Linux 20.04): macOS Sonoma 14.2.1
- [x] OS architecture (e.g. amd64): arm64
- [x] pyenv version: 2.3.35
- [x] pyenv-virtualenv version: 1.1.5
- [x] Python version: 3.10
- [ ] virtualenv version (if installed):
- [ ] Please attach the debug log of a faulty Pyenv invocation as a gist

Using `.python-version` like this

```
3.10.13/envs/dm-import-scripts
```

to auto-activate enviroments breaks other tools which do not expect this syntax in `.python-version`, e.g. [GitHub `setup-python` action](github.com/actions/setup-python):

```console
Warning: Neither 'python-version' nor 'python-version-file' inputs were supplied. Attempting to find '.python-version' file.
Resolved .python-version as 3.10.13/envs/virtualenv
Installed versions
  Version 3.10.13/envs/virtualenv was not found in the local cache
  Error: The version '3.10.13/envs/virtualenv' with architecture 'x64' was not found for Ubuntu 22.04.
  The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```

It would be reasonable not to use `.python-version` for this or at least use some non-breaking syntax (maybe a comment or something?).

**Comment by native-api** [comment]
This looks like a problem in the Github action rather than Pyenv.

Moreover, the [action's documentation](https://github.com/actions/setup-python/blob/main/action.yml) and the error message shows a way to override the value from `.python-version`: with `python-version:` .

**Comment by krystof-k** [comment]
I don't think so, the action or any other tool cannot know of Pyenv syntax.

Unfortunately, there is no official standard for `.*-version` files, however the common convention is to include only the version number and nothing else. If Pyenv wishes to provide additional configuration options, it would be better to use a different file, such as `.pyenvrc`, instead of the `.python-version` file.

**Comment by native-api** [comment]
Pyenv is the standard for `.python-version` syntax. It is the software that introduced it.

---

Now, a pointer to a virtual environment like the one you gave is actually rather created by a Pyenv plugin, Pyenv-virtualenv.
A pointer like that does specify the base version (as the 1st path component), but the further data only specifies that it's a virtual environment, nothing about its details.

---

As such, if you plan to use `.python-version` in CI, you should either only specify a base version there, or, if you need different settings for local use and for CI, use another setting to govern the CI as specificed above.

Alternatively, a CI may choose to support a pointer like that, talking only the base version name (since there's no need to make a virtualenv in a CI job).
