### ISSUE TITLE
Cannot create virtualenv

### ISSUE THREAD

**Issue by HarshNarayanJha** [pyenv/pyenv-virtualenv#487]
### Prerequisite
* [x] Make sure your problem is not listed in [the common build problems](https://github.com/pyenv/pyenv/wiki/Common-build-problems).
* [x] Make sure no duplicated issue has already been reported in [the pyenv-virtualenv issues](https://github.com/pyenv/pyenv-virtualenv/issues). You should look in closed issues, too.
* [x] Make sure you are not asking us to help solving your specific issue.
  * GitHub issues is opened mainly for development purposes. If you want to ask someone to help solving your problem, go to some community site like [Gitter](https://gitter.im/yyuu/pyenv), [StackOverflow](https://stackoverflow.com/questions/tagged/pyenv), etc.
* [x] Make sure your problem is not derived from packaging (e.g. [Homebrew](https://brew.sh)).
  * Please refer to the package documentation for the installation issues, etc.
* [x] Make sure your problem is not derived from other plugins.
  * This repository is maintaining the `pyenv-virtualenv` plugin only. Please refrain from reporting issues of other plugins here.

### Description
- [x] Platform information: Garuda Linux
- [x] OS architecture: x86_64
- [x] pyenv version: pyenv 2.4.7
- [x] pyenv-virtualenv version: pyenv-virtualenv 1.2.4
- [x] Python version: Python 3.12.4
- [x] virtualenv version (if installed): virtualenv 20.26.3
- [x] Please attach the debug log of a faulty Pyenv invocation as a gist

Running `pyenv virtualenv env` or `pyenv virtualenv 3.12.4 env` gives a error
`pyenv: no installed versions match the prefix `-f'`

https://gist.github.com/HarshNarayanJha/e7fcf4e548de0c69708c6cc1bd2b9e3e

**Comment by HarshNarayanJha** [comment]
It is saying already up to date?
```fish
Updating /home/harshnj/.pyenv/plugins/pyenv-doctor...
From https://github.com/pyenv/pyenv-doctor
* branch            master     -> FETCH_HEAD
Already up to date.
Updating /home/harshnj/.pyenv/plugins/pyenv-pip-migrate...
From https://github.com/pyenv/pyenv-pip-migrate
* branch            master     -> FETCH_HEAD
Already up to date.
Updating /home/harshnj/.pyenv/plugins/pyenv-pip-update...
From https://github.com/massongit/pyenv-pip-update
* branch            master     -> FETCH_HEAD
Already up to date.
Updating /home/harshnj/.pyenv/plugins/pyenv-update...
From https://github.com/pyenv/pyenv-update
* branch            master     -> FETCH_HEAD
Already up to date.
Updating /home/harshnj/.pyenv/plugins/pyenv-virtualenv...
From https://github.com/pyenv/pyenv-virtualenv
* branch            master     -> FETCH_HEAD
Already up to date.
```

**Comment by native-api** [comment]
> It is saying already up to date?

I don't see Pyenv itself in the list. It's probably installed somewhere else.

**Comment by HarshNarayanJha** [comment]
Right, not updated in arch repos yet (2 days?)

**Comment by native-api** [comment]
In the meantime, you can downgrade to `v1.2.4` or to https://github.com/pyenv/pyenv-virtualenv/commit/cf45718a1b0e86d7a53c8d03d11151306a080ec7

```
cd ~/.pyenv/plugins/pyenv-virtualenv
git checkout <commit>
```

**Comment by HarshNarayanJha** [comment]
Checkout works right now. Probably package will update soon

Strange, it now shows latest version online, but hasn't reached my system yet.

Closing

**Comment by HarshNarayanJha** [comment]
Update arrived
