### ISSUE TITLE
Version mismatch between `pyenv virtualenv` and `pyenv-virtualenv` when installed using homebrew

### ISSUE THREAD

**Issue by gtebbutt** [pyenv/pyenv-virtualenv#493]
I'm having some difficulty getting the latest version of the plugin based on the instructions in the README. Installing on macOS 14.7.1 (Sonoma) using `brew install pyenv` gives the following:

```zsh
~ % pyenv --version
pyenv 2.4.21

~ % pyenv virtualenv --version
pyenv-virtualenv 1.2.1 (virtualenv unknown)

~ % pyenv-virtualenv
zsh: command not found: pyenv-virtualenv
```

Adding `pyenv-virtualenv` explicitly using `brew install pyenv-virtualenv` then gives:

```zsh
~ % pyenv --version
pyenv 2.4.21

~ % pyenv virtualenv --version  
pyenv-virtualenv 1.2.1 (virtualenv unknown)

~ % pyenv-virtualenv --version
/opt/homebrew/bin/pyenv-virtualenv: line 116: pyenv-version-name: command not found
/opt/homebrew/bin/pyenv-virtualenv: line 151: pyenv-prefix: command not found
pyenv-virtualenv 1.2.4 (virtualenv unknown)
```

The same happens after uninstalling both and running only `brew install pyenv-virtualenv` (letting it pull in `pyenv` as a dependency). The workaround for now is easy enough, just using the version with the `-` rather than without, but it'd be good to know why this is likely to be happening? I was pretty confused about still seeing #485 on the latest version until I spotted the mismatch.

**Comment by gtebbutt** [comment]
Workaround actually doesn't seem so easy, actually... The `pyenv-virtualenv` command can't see any of the python versions installed that are visible to `pyenv virtualenv`.

**Comment by native-api** [comment]
You are not supposed to run `pyenv-virtualenv` directly, that's why it's not on PATH. Running it via subcommand like `pyenv virtualenv` is the intended way.

**Comment by gtebbutt** [comment]
Hi, thanks for the quick follow up. I understand that `pyenv-virtualenv` isn't intended to be run directly (although it is on `PATH`, via `/opt/homebrew/bin`, at least on my system) the issue is that installing the `pyenv-virtualenv` package doesn't seem to affect the version used by the `pyenv virtualenv` command. 

I was just calling it directly to demonstrate that the second `brew install` command is bringing in version 1.2.4 as expected, but that it isn't being used by `pyenv virtualenv`.

**Comment by native-api** [comment]
We are not responsible for the `pyenv-virtualenv` Homebrew package. The errors you're getting for it look like incorrect packaging.

In stock Pyenv, `pyenv-virtualenv` resides inside `$(pyenv root)/plugins/pyenv-virtualenv/bin` which is only added to `PATH` internally, by the root `pyenv` launcher, together with `$(pyenv root)/libexec` where core subcommands like `pyenv-version-name` and `pyenv-prefix` reside.

**Comment by native-api** [comment]
About your original question: you must have two version of Pyenv-Virtualenv: one inside of `$(pyenv root)/plugins` and one installed with Homebrew.

Since the Homebrew version seems to be broken, I suggest you uninstall it and upgrade the version in `plugins` -- with `pyenv update` if you have it (if not, you can install it from https://github.com/pyenv/pyenv-update) or manually with `cd "$(pyenv root)/plugins/pyenv-virtualenv"; git pull`.

**Comment by gtebbutt** [comment]
Got you, really appreciate the help! I saw that the Homebrew packages were recommended in the README and thought they were maintained from here - my mistake on that one. 

For anyone having the same issue later: it looks like there were indeed two versions of the plugin, and the `$(pyenv root)/plugins` one was taking precedence even when `pyenv` and `pyenv-virtualenv` were installed with Homebrew. I'm not certain how the older plugin got there - could have been from a previous Homebrew packaged version, or maybe from inadvertently running `pyenv update` rather than `brew upgrade ...` at some point in the past - but either way it was causing the newer version of the plugin to be ignored and wasn't being removed or replaced when uninstalling/reinstalling/upgrading with Homebrew. 

Uninstalled everything, manually deleted `$(pyenv root)/plugins`, and then reinstalled using `brew install pyenv pyenv-virtualenv` and it's working as expected now. It looks like the Homebrew package doesn't keep a `plugins` folder in the pyenv root at all, so that's probably a decent rule of thumb to check if something's gone wrong with a `brew install`ed version.
